const MISSILE_IDS: Readonly<Record<string, number>> = {
  CONST_ANI_SPEAR: 1,
  CONST_ANI_BOLT: 2,
  CONST_ANI_ARROW: 3,
  CONST_ANI_FIRE: 4,
  CONST_ANI_ENERGY: 5,
  CONST_ANI_POISONARROW: 6,
  CONST_ANI_BURSTARROW: 7,
  CONST_ANI_THROWINGSTAR: 8,
  CONST_ANI_THROWINGKNIFE: 9,
  CONST_ANI_SMALLSTONE: 10,
  CONST_ANI_DEATH: 11,
  CONST_ANI_LARGEROCK: 12,
  CONST_ANI_SNOWBALL: 13,
  CONST_ANI_POWERBOLT: 14,
  CONST_ANI_POISON: 15,
  CONST_ANI_HUNTINGSPEAR: 17,
  CONST_ANI_ENCHANTEDSPEAR: 18,
  CONST_ANI_GREENSTAR: 20,
  CONST_ANI_ROYALSPEAR: 21,
  CONST_ANI_SNIPERARROW: 22,
  CONST_ANI_ONYXARROW: 23,
  CONST_ANI_PIERCINGBOLT: 24,
  CONST_ANI_WHIRLWINDSWORD: 25,
  CONST_ANI_WHIRLWINDAXE: 26,
  CONST_ANI_WHIRLWINDCLUB: 27,
  CONST_ANI_ETHEREALSPEAR: 28,
  CONST_ANI_ICE: 29,
  CONST_ANI_EARTH: 30,
  CONST_ANI_HOLY: 31,
  CONST_ANI_SUDDENDEATH: 32,
  CONST_ANI_FLASHARROW: 33,
  CONST_ANI_FLAMMINGARROW: 34,
  CONST_ANI_ENERGYBALL: 36,
  CONST_ANI_SMALLEARTH: 37,
  CONST_ANI_SMALLHOLY: 38,
  CONST_ANI_SMALLICE: 39,
  CONST_ANI_EXPLOSION: 40,
  CONST_ANI_EARTHARROW: 41,
  CONST_ANI_ENVENOMEDARROW: 42,
  CONST_ANI_LEAFSTAR: 43,
};

export function getMissileId(
  missile: string | number | undefined,
): number | undefined {
  if (typeof missile === "number") {
    return Math.max(1, Math.min(255, Math.floor(missile)));
  }
  return missile ? (MISSILE_IDS[missile] ?? 3) : undefined;
}
