import type { SpellDefinition } from "./Spell";

const ALL_VOCATIONS = [
  "Knight",
  "Paladin",
  "Sorcerer",
  "Druid",
  "Elite Knight",
  "Royal Paladin",
  "Master Sorcerer",
  "Elder Druid",
] as const;

const MAGES = [
  "Sorcerer",
  "Druid",
  "Master Sorcerer",
  "Elder Druid",
] as const;

const SORCERERS = ["Sorcerer", "Master Sorcerer"] as const;
const DRUIDS = ["Druid", "Elder Druid"] as const;
const KNIGHTS = ["Knight", "Elite Knight"] as const;
const PALADINS = ["Paladin", "Royal Paladin"] as const;

const SPELLS: ReadonlyArray<SpellDefinition> = [
  {
    id: "light-healing",
    name: "Light Healing",
    origin: "spell",
    vocations: ALL_VOCATIONS,
    requiredLevel: 1,
    requiredMagicLevel: 0,
    manaCost: 20,
    soulCost: 0,
    cooldownGroup: "healing",
    cooldownMs: 1_000,
    range: 0,
    lineOfSight: false,
    targetKinds: ["self"],
    area: { shape: "single" },
    damageType: "healing",
    formula: {
      minimumBase: 20,
      maximumBase: 30,
      levelFactor: 0.2,
      magicFactor: 2,
    },
    effectId: 13,
  },
  {
    id: "energy-strike",
    name: "Energy Strike",
    origin: "spell",
    vocations: MAGES,
    requiredLevel: 1,
    requiredMagicLevel: 0,
    manaCost: 6,
    soulCost: 0,
    cooldownGroup: "attack",
    cooldownMs: 1_000,
    range: 4,
    lineOfSight: true,
    targetKinds: ["attack-target", "creature"],
    area: { shape: "single" },
    damageType: "energy",
    formula: {
      minimumBase: 8,
      maximumBase: 18,
      levelFactor: 0.2,
      magicFactor: 1.8,
    },
    effectId: 12,
    missileId: 5,
  },
  {
    id: "ice-wave",
    name: "Ice Wave",
    origin: "spell",
    vocations: DRUIDS,
    requiredLevel: 8,
    requiredMagicLevel: 1,
    manaCost: 25,
    soulCost: 0,
    cooldownGroup: "attack",
    cooldownMs: 2_000,
    range: 5,
    lineOfSight: true,
    targetKinds: ["attack-target", "creature"],
    area: { shape: "cone", length: 5, spread: 3 },
    damageType: "ice",
    formula: {
      minimumBase: 15,
      maximumBase: 28,
      levelFactor: 0.25,
      magicFactor: 2,
    },
    effectId: 42,
  },
  {
    id: "fire-bomb",
    name: "Fire Bomb",
    origin: "spell",
    vocations: [...SORCERERS, ...DRUIDS],
    requiredLevel: 15,
    requiredMagicLevel: 3,
    manaCost: 85,
    soulCost: 1,
    cooldownGroup: "attack",
    cooldownMs: 6_000,
    range: 5,
    lineOfSight: true,
    targetKinds: ["attack-target", "creature", "position"],
    area: { shape: "circle", radius: 1 },
    damageType: "fire",
    formula: {
      minimumBase: 20,
      maximumBase: 35,
      levelFactor: 0.2,
      magicFactor: 1.5,
    },
    effectId: 7,
    missileId: 4,
    condition: {
      type: "fire",
      durationMs: 10_000,
      magnitude: 5,
      tickIntervalMs: 2_000,
      damageType: "fire",
      effectId: 16,
    },
  },
  {
    id: "haste",
    name: "Haste",
    origin: "spell",
    vocations: ALL_VOCATIONS,
    requiredLevel: 14,
    requiredMagicLevel: 0,
    manaCost: 60,
    soulCost: 0,
    cooldownGroup: "support",
    cooldownMs: 2_000,
    range: 0,
    lineOfSight: false,
    targetKinds: ["self"],
    area: { shape: "single" },
    damageType: "healing",
    formula: {
      minimumBase: 0,
      maximumBase: 0,
      levelFactor: 0,
      magicFactor: 0,
    },
    effectId: 15,
    condition: {
      type: "haste",
      durationMs: 30_000,
      magnitude: 60,
      effectId: 15,
    },
  },
  {
    id: "magic-shield",
    name: "Magic Shield",
    origin: "spell",
    vocations: MAGES,
    requiredLevel: 14,
    requiredMagicLevel: 2,
    manaCost: 50,
    soulCost: 0,
    cooldownGroup: "support",
    cooldownMs: 2_000,
    range: 0,
    lineOfSight: false,
    targetKinds: ["self"],
    area: { shape: "single" },
    damageType: "healing",
    formula: {
      minimumBase: 0,
      maximumBase: 0,
      levelFactor: 0,
      magicFactor: 0,
    },
    effectId: 13,
    condition: {
      type: "magic-shield",
      durationMs: 60_000,
      effectId: 13,
    },
  },
  {
    id: "ultimate-healing",
    name: "Ultimate Healing",
    origin: "spell",
    vocations: ALL_VOCATIONS,
    requiredLevel: 20,
    requiredMagicLevel: 3,
    manaCost: 160,
    soulCost: 0,
    cooldownGroup: "healing",
    cooldownMs: 2_000,
    range: 0,
    lineOfSight: false,
    targetKinds: ["self"],
    area: { shape: "single" },
    damageType: "healing",
    formula: {
      minimumBase: 80,
      maximumBase: 120,
      levelFactor: 0.5,
      magicFactor: 4,
    },
    effectId: 13,
  },
  {
    id: "front-sweep",
    name: "Front Sweep",
    origin: "spell",
    vocations: KNIGHTS,
    requiredLevel: 8,
    requiredMagicLevel: 0,
    manaCost: 20,
    soulCost: 0,
    cooldownGroup: "attack",
    cooldownMs: 2_000,
    range: 3,
    lineOfSight: true,
    targetKinds: ["attack-target", "creature"],
    area: { shape: "cone", length: 3, spread: 3 },
    damageType: "physical",
    formula: {
      minimumBase: 12,
      maximumBase: 25,
      levelFactor: 0.4,
      magicFactor: 0,
    },
    effectId: 10,
  },
  {
    id: "holy-strike",
    name: "Holy Strike",
    origin: "spell",
    vocations: PALADINS,
    requiredLevel: 8,
    requiredMagicLevel: 1,
    manaCost: 20,
    soulCost: 0,
    cooldownGroup: "attack",
    cooldownMs: 1_500,
    range: 5,
    lineOfSight: true,
    targetKinds: ["attack-target", "creature"],
    area: { shape: "single" },
    damageType: "holy",
    formula: {
      minimumBase: 12,
      maximumBase: 24,
      levelFactor: 0.3,
      magicFactor: 1.4,
    },
    effectId: 40,
    missileId: 31,
  },
  {
    id: "sudden-death-rune",
    name: "Sudden Death Rune",
    origin: "rune",
    runeItemTypeId: 3155,
    vocations: ALL_VOCATIONS,
    requiredLevel: 45,
    requiredMagicLevel: 15,
    manaCost: 0,
    soulCost: 0,
    cooldownGroup: "rune",
    cooldownMs: 2_000,
    range: 7,
    lineOfSight: true,
    targetKinds: ["attack-target", "creature"],
    area: { shape: "single" },
    damageType: "death",
    formula: {
      minimumBase: 50,
      maximumBase: 90,
      levelFactor: 0.5,
      magicFactor: 3,
    },
    effectId: 18,
    missileId: 32,
  },
  {
    id: "ultimate-healing-rune",
    name: "Ultimate Healing Rune",
    origin: "rune",
    runeItemTypeId: 3160,
    vocations: ALL_VOCATIONS,
    requiredLevel: 24,
    requiredMagicLevel: 4,
    manaCost: 0,
    soulCost: 0,
    cooldownGroup: "rune",
    cooldownMs: 2_000,
    range: 0,
    lineOfSight: false,
    targetKinds: ["self"],
    area: { shape: "single" },
    damageType: "healing",
    formula: {
      minimumBase: 100,
      maximumBase: 160,
      levelFactor: 0.5,
      magicFactor: 4,
    },
    effectId: 13,
  },
  {
    id: "stone-shower-rune",
    name: "Stone Shower Rune",
    origin: "rune",
    runeItemTypeId: 3175,
    vocations: ALL_VOCATIONS,
    requiredLevel: 28,
    requiredMagicLevel: 4,
    manaCost: 0,
    soulCost: 0,
    cooldownGroup: "rune",
    cooldownMs: 2_000,
    range: 7,
    lineOfSight: true,
    targetKinds: ["attack-target", "creature", "position"],
    area: { shape: "circle", radius: 2 },
    damageType: "earth",
    formula: {
      minimumBase: 30,
      maximumBase: 55,
      levelFactor: 0.35,
      magicFactor: 2,
    },
    effectId: 45,
    missileId: 30,
    condition: {
      type: "poison",
      durationMs: 12_000,
      magnitude: 4,
      tickIntervalMs: 2_000,
      damageType: "earth",
      effectId: 17,
    },
  },
];

export class SpellRegistry {
  private readonly byId = new Map(SPELLS.map((spell) => [spell.id, spell]));
  private readonly byRuneTypeId = new Map(
    SPELLS.flatMap((spell) =>
      spell.runeItemTypeId ? [[spell.runeItemTypeId, spell] as const] : [],
    ),
  );

  get(spellId: string): SpellDefinition | undefined {
    return this.byId.get(spellId);
  }

  getRune(itemTypeId: number): SpellDefinition | undefined {
    return this.byRuneTypeId.get(itemTypeId);
  }
}
