import type { Vocation } from "./Vocation";

/**
 * Project-native conversion of Canary's pinned vocations.xml. This is static
 * balance data; Canary XML/C++ is never loaded or executed by the game server.
 */
export const VOCATION_DEFINITIONS = {
  Knight: {
    id: "Knight",
    numericId: 4,
    baseVocation: "Knight",
    promotedFrom: null,
    promotedVocation: "Elite Knight",
    starter: true,
    gains: { health: 15, mana: 5, capacity: 25 },
    regeneration: {
      healthIntervalMs: 6_000,
      healthAmount: 1,
      manaIntervalMs: 6_000,
      manaAmount: 2,
      soulIntervalMs: 120_000,
      soulAmount: 1,
    },
    maxSoul: 100,
    attackSpeedMs: 2_000,
    baseSpeed: 110,
    magicProgressionMultiplier: 3,
    skillProgressionMultipliers: {
      fist: 1.1,
      club: 1.1,
      sword: 1.1,
      axe: 1.1,
      distance: 1.4,
      shielding: 1.1,
      fishing: 1.1,
    },
    formulas: {
      meleeDamage: 1,
      distanceDamage: 1,
      defense: 1,
      armor: 1,
      mitigation: 1.3,
      primaryShield: 2.05,
      secondaryShield: 1.25,
    },
    client: {
      name: "Knight",
      description: "Stalwart front-line fighter with melee mastery.",
      avatarLookType: 1593,
    },
  },
  Paladin: {
    id: "Paladin",
    numericId: 3,
    baseVocation: "Paladin",
    promotedFrom: null,
    promotedVocation: "Royal Paladin",
    starter: true,
    gains: { health: 10, mana: 15, capacity: 20 },
    regeneration: {
      healthIntervalMs: 8_000,
      healthAmount: 1,
      manaIntervalMs: 4_000,
      manaAmount: 2,
      soulIntervalMs: 120_000,
      soulAmount: 1,
    },
    maxSoul: 100,
    attackSpeedMs: 2_000,
    baseSpeed: 110,
    magicProgressionMultiplier: 1.4,
    skillProgressionMultipliers: {
      fist: 1.2,
      club: 1.2,
      sword: 1.2,
      axe: 1.2,
      distance: 1.1,
      shielding: 1.1,
      fishing: 1.1,
    },
    formulas: {
      meleeDamage: 1,
      distanceDamage: 1,
      defense: 1,
      armor: 1,
      mitigation: 1.28,
      primaryShield: 2.08,
      secondaryShield: 1.2,
    },
    client: {
      name: "Paladin",
      description: "Versatile ranged hunter with holy magic.",
      avatarLookType: 1594,
    },
  },
  Sorcerer: {
    id: "Sorcerer",
    numericId: 1,
    baseVocation: "Sorcerer",
    promotedFrom: null,
    promotedVocation: "Master Sorcerer",
    starter: true,
    gains: { health: 5, mana: 30, capacity: 10 },
    regeneration: {
      healthIntervalMs: 12_000,
      healthAmount: 1,
      manaIntervalMs: 3_000,
      manaAmount: 2,
      soulIntervalMs: 120_000,
      soulAmount: 1,
    },
    maxSoul: 100,
    attackSpeedMs: 2_000,
    baseSpeed: 110,
    magicProgressionMultiplier: 1.1,
    skillProgressionMultipliers: {
      fist: 1.5,
      club: 2,
      sword: 2,
      axe: 2,
      distance: 2,
      shielding: 1.5,
      fishing: 1.1,
    },
    formulas: {
      meleeDamage: 1,
      distanceDamage: 1,
      defense: 1,
      armor: 1,
      mitigation: 1.26,
      primaryShield: 2,
      secondaryShield: 1.2,
    },
    client: {
      name: "Sorcerer",
      description: "Master of destructive arcane magic.",
      avatarLookType: 1595,
    },
  },
  Druid: {
    id: "Druid",
    numericId: 2,
    baseVocation: "Druid",
    promotedFrom: null,
    promotedVocation: "Elder Druid",
    starter: true,
    gains: { health: 5, mana: 30, capacity: 10 },
    regeneration: {
      healthIntervalMs: 12_000,
      healthAmount: 1,
      manaIntervalMs: 3_000,
      manaAmount: 2,
      soulIntervalMs: 120_000,
      soulAmount: 1,
    },
    maxSoul: 100,
    attackSpeedMs: 2_000,
    baseSpeed: 110,
    magicProgressionMultiplier: 1.1,
    skillProgressionMultipliers: {
      fist: 1.5,
      club: 1.8,
      sword: 1.8,
      axe: 1.8,
      distance: 1.8,
      shielding: 1.5,
      fishing: 1.1,
    },
    formulas: {
      meleeDamage: 1,
      distanceDamage: 1,
      defense: 1,
      armor: 1,
      mitigation: 1.26,
      primaryShield: 2,
      secondaryShield: 1.2,
    },
    client: {
      name: "Druid",
      description: "Nature mage focused on healing and ice.",
      avatarLookType: 1596,
    },
  },
  Monk: {
    id: "Monk",
    numericId: 9,
    baseVocation: "Monk",
    promotedFrom: null,
    promotedVocation: "Exalted Monk",
    starter: true,
    gains: { health: 10, mana: 10, capacity: 25 },
    regeneration: {
      healthIntervalMs: 6_000,
      healthAmount: 1,
      manaIntervalMs: 6_000,
      manaAmount: 2,
      soulIntervalMs: 120_000,
      soulAmount: 1,
    },
    maxSoul: 100,
    attackSpeedMs: 2_000,
    baseSpeed: 110,
    magicProgressionMultiplier: 1.3,
    skillProgressionMultipliers: {
      fist: 1.1,
      club: 1.5,
      sword: 1.5,
      axe: 1.5,
      distance: 2,
      shielding: 1.2,
      fishing: 1.1,
    },
    formulas: {
      meleeDamage: 1,
      distanceDamage: 1,
      defense: 1,
      armor: 1,
      mitigation: 1.28,
      primaryShield: 2.08,
      secondaryShield: 1.2,
    },
    client: {
      name: "Monk",
      description: "Disciplined martial artist specializing in fist combat.",
      avatarLookType: 1823,
    },
  },
  "Elite Knight": {
    id: "Elite Knight",
    numericId: 8,
    baseVocation: "Knight",
    promotedFrom: "Knight",
    promotedVocation: null,
    starter: false,
    gains: { health: 15, mana: 5, capacity: 25 },
    regeneration: {
      healthIntervalMs: 4_000,
      healthAmount: 1,
      manaIntervalMs: 6_000,
      manaAmount: 2,
      soulIntervalMs: 15_000,
      soulAmount: 1,
    },
    maxSoul: 200,
    attackSpeedMs: 2_000,
    baseSpeed: 110,
    magicProgressionMultiplier: 3,
    skillProgressionMultipliers: {
      fist: 1.4,
      club: 1.1,
      sword: 1.1,
      axe: 1.1,
      distance: 1.1,
      shielding: 1.1,
      fishing: 1.1,
    },
    formulas: {
      meleeDamage: 1,
      distanceDamage: 1,
      defense: 1,
      armor: 1,
      mitigation: 1.3,
      primaryShield: 2.05,
      secondaryShield: 1.25,
    },
    client: {
      name: "Elite Knight",
      description: "Promoted knight with faster regeneration.",
      avatarLookType: 1593,
    },
  },
  "Royal Paladin": {
    id: "Royal Paladin",
    numericId: 7,
    baseVocation: "Paladin",
    promotedFrom: "Paladin",
    promotedVocation: null,
    starter: false,
    gains: { health: 10, mana: 15, capacity: 20 },
    regeneration: {
      healthIntervalMs: 6_000,
      healthAmount: 1,
      manaIntervalMs: 3_000,
      manaAmount: 2,
      soulIntervalMs: 15_000,
      soulAmount: 1,
    },
    maxSoul: 200,
    attackSpeedMs: 2_000,
    baseSpeed: 110,
    magicProgressionMultiplier: 1.4,
    skillProgressionMultipliers: {
      fist: 1.2,
      club: 1.2,
      sword: 1.2,
      axe: 1.2,
      distance: 1.1,
      shielding: 1.1,
      fishing: 1.1,
    },
    formulas: {
      meleeDamage: 1,
      distanceDamage: 1,
      defense: 1,
      armor: 1,
      mitigation: 1.28,
      primaryShield: 2.08,
      secondaryShield: 1.2,
    },
    client: {
      name: "Royal Paladin",
      description: "Promoted paladin with faster regeneration.",
      avatarLookType: 1594,
    },
  },
  "Master Sorcerer": {
    id: "Master Sorcerer",
    numericId: 5,
    baseVocation: "Sorcerer",
    promotedFrom: "Sorcerer",
    promotedVocation: null,
    starter: false,
    gains: { health: 5, mana: 30, capacity: 10 },
    regeneration: {
      healthIntervalMs: 12_000,
      healthAmount: 1,
      manaIntervalMs: 2_000,
      manaAmount: 2,
      soulIntervalMs: 15_000,
      soulAmount: 1,
    },
    maxSoul: 200,
    attackSpeedMs: 2_000,
    baseSpeed: 110,
    magicProgressionMultiplier: 1.1,
    skillProgressionMultipliers: {
      fist: 1.5,
      club: 2,
      sword: 2,
      axe: 2,
      distance: 2,
      shielding: 1.5,
      fishing: 1.1,
    },
    formulas: {
      meleeDamage: 1,
      distanceDamage: 1,
      defense: 1,
      armor: 1,
      mitigation: 1.26,
      primaryShield: 2,
      secondaryShield: 1.2,
    },
    client: {
      name: "Master Sorcerer",
      description: "Promoted sorcerer with faster regeneration.",
      avatarLookType: 1595,
    },
  },
  "Elder Druid": {
    id: "Elder Druid",
    numericId: 6,
    baseVocation: "Druid",
    promotedFrom: "Druid",
    promotedVocation: null,
    starter: false,
    gains: { health: 5, mana: 30, capacity: 10 },
    regeneration: {
      healthIntervalMs: 12_000,
      healthAmount: 1,
      manaIntervalMs: 2_000,
      manaAmount: 2,
      soulIntervalMs: 15_000,
      soulAmount: 1,
    },
    maxSoul: 200,
    attackSpeedMs: 2_000,
    baseSpeed: 110,
    magicProgressionMultiplier: 1.1,
    skillProgressionMultipliers: {
      fist: 1.5,
      club: 1.8,
      sword: 1.8,
      axe: 1.8,
      distance: 1.8,
      shielding: 1.5,
      fishing: 1.1,
    },
    formulas: {
      meleeDamage: 1,
      distanceDamage: 1,
      defense: 1,
      armor: 1,
      mitigation: 1.26,
      primaryShield: 2,
      secondaryShield: 1.2,
    },
    client: {
      name: "Elder Druid",
      description: "Promoted druid with faster regeneration.",
      avatarLookType: 1596,
    },
  },
  "Exalted Monk": {
    id: "Exalted Monk",
    numericId: 10,
    baseVocation: "Monk",
    promotedFrom: "Monk",
    promotedVocation: null,
    starter: false,
    gains: { health: 10, mana: 10, capacity: 25 },
    regeneration: {
      healthIntervalMs: 4_000,
      healthAmount: 1,
      manaIntervalMs: 6_000,
      manaAmount: 2,
      soulIntervalMs: 15_000,
      soulAmount: 1,
    },
    maxSoul: 200,
    attackSpeedMs: 2_000,
    baseSpeed: 110,
    magicProgressionMultiplier: 1.3,
    skillProgressionMultipliers: {
      fist: 1.1,
      club: 1.5,
      sword: 1.5,
      axe: 1.5,
      distance: 2,
      shielding: 1.2,
      fishing: 1.1,
    },
    formulas: {
      meleeDamage: 1,
      distanceDamage: 1,
      defense: 1,
      armor: 1,
      mitigation: 1.28,
      primaryShield: 2.08,
      secondaryShield: 1.2,
    },
    client: {
      name: "Exalted Monk",
      description: "Promoted monk with faster health regeneration.",
      avatarLookType: 1823,
    },
  },
} as const satisfies Readonly<Record<string, Vocation>>;
