import { describe, expect, it } from "vitest";
import fixtureData from "./vocationCoefficientFixture.json";
import { VOCATION_DEFINITIONS } from "./vocationDefinitions";

/**
 * Every field of a vocation definition is either a Canary gameplay coefficient
 * (checked against the pinned fixture generated by
 * tools/buildVocationCoefficientFixture.mjs) or explicitly classified as
 * structural/display. A drifted coefficient fails the deep-equal; a brand-new
 * field fails the completeness check until it is classified and, if gameplay,
 * added to the fixture.
 */
const GAMEPLAY_KEYS = [
  "numericId",
  "gains",
  "regeneration",
  "maxSoul",
  "attackSpeedMs",
  "baseSpeed",
  "magicProgressionMultiplier",
  "skillProgressionMultipliers",
  "formulas",
] as const;

// Structural identity and client/display data — not Canary balance coefficients.
const NON_GAMEPLAY_KEYS = new Set([
  "id",
  "baseVocation",
  "promotedFrom",
  "promotedVocation",
  "starter",
  "client",
]);

const fixture = fixtureData.vocations as Record<
  string,
  Record<string, unknown>
>;

const pick = (
  source: Record<string, unknown>,
  keys: ReadonlyArray<string>,
): Record<string, unknown> => {
  const out: Record<string, unknown> = {};
  for (const key of keys) out[key] = source[key];
  return out;
};

describe("vocation coefficient fixtures", () => {
  it("covers exactly the shipped vocations", () => {
    expect(Object.keys(fixture).sort()).toEqual(
      Object.keys(VOCATION_DEFINITIONS).sort(),
    );
  });

  for (const [name, definition] of Object.entries(VOCATION_DEFINITIONS)) {
    it(`matches every pinned gameplay coefficient for ${name}`, () => {
      const expected = fixture[name];
      expect(expected, `no fixture entry for ${name}`).toBeDefined();
      expect(
        pick(definition as Record<string, unknown>, GAMEPLAY_KEYS),
      ).toEqual(expected);
    });

    it(`classifies every field of ${name} as gameplay or non-gameplay`, () => {
      const classified = new Set<string>([
        ...GAMEPLAY_KEYS,
        ...NON_GAMEPLAY_KEYS,
      ]);
      const unclassified = Object.keys(definition).filter(
        (key) => !classified.has(key),
      );
      expect(
        unclassified,
        `unclassified coefficient(s) on ${name}: ${unclassified.join(", ")}`,
      ).toEqual([]);
    });
  }
});
