interface SpellIconArtwork {
  sheet: "current" | "legacy";
  index: number;
}

// Synced with OpenTibiaBR OTClient spell client IDs at bdea0b23b4a738809d698cb7e4f88a299dd6bffc.
const CURRENT_SPELL_ICON_INDEXES: Readonly<Record<string, number>> = {
  "adana-ani": 70,
  "adana-mort": 92,
  "adana-pox": 88,
  "adeta-sio": 89,
  "adevo-grav-flam": 80,
  "adevo-grav-pox": 68,
  "adevo-grav-tera": 71,
  "adevo-grav-vis": 84,
  "adevo-grav-vita": 60,
  "adevo-ina": 90,
  "adevo-mas-flam": 81,
  "adevo-mas-grav-flam": 79,
  "adevo-mas-grav-pox": 67,
  "adevo-mas-grav-vis": 83,
  "adevo-mas-hur": 82,
  "adevo-mas-pox": 69,
  "adevo-mas-vis": 85,
  "adevo-res-flam": 66,
  "adito-grav": 86,
  "adito-tera": 87,
  "adori-dis-min-vis": 129,
  "adori-flam": 78,
  "adori-frigo": 74,
  "adori-gran-mort": 63,
  "adori-infir-mas-tera": 64,
  "adori-infir-vis": 72,
  "adori-mas-flam": 77,
  "adori-mas-frigo": 91,
  "adori-mas-tera": 64,
  "adori-mas-vis": 62,
  "adori-min-vis": 72,
  "adori-san": 75,
  "adori-tera": 65,
  "adori-vis": 76,
  "adura-gran": 73,
  "adura-vita": 61,
  "antidote-rune": 88,
  "avalanche-rune": 91,
  "exana-flam": 12,
  "exana-ina": 94,
  "exana-kor": 11,
  "exana-mort": 10,
  "exana-pox": 9,
  "exana-vis": 13,
  "exana-vita": 146,
  "exeta-con": 103,
  "exeta-vis": 141,
  "exevo-con": 105,
  "exevo-con-flam": 108,
  "exevo-dis-flam-hur": 128,
  "exevo-flam-hur": 43,
  "exevo-frigo-hur": 44,
  "exevo-gran-flam-hur": 102,
  "exevo-gran-frigo-hur": 45,
  "exevo-gran-mas-flam": 48,
  "exevo-gran-mas-frigo": 49,
  "exevo-gran-mas-tera": 47,
  "exevo-gran-mas-vis": 51,
  "exevo-gran-mort": 141,
  "exevo-gran-vis-lux": 41,
  "exevo-infir-con": 137,
  "exevo-infir-flam-hur": 131,
  "exevo-infir-frigo-hur": 135,
  "exevo-mas-san": 39,
  "exevo-tera-hur": 46,
  "exevo-vis-hur": 42,
  "exevo-vis-lux": 40,
  "exori": 20,
  "exori-amp-vis": 50,
  "exori-con": 17,
  "exori-flam": 25,
  "exori-frigo": 31,
  "exori-gran": 21,
  "exori-gran-con": 58,
  "exori-gran-flam": 26,
  "exori-gran-frigo": 32,
  "exori-gran-ico": 23,
  "exori-gran-tera": 35,
  "exori-gran-vis": 29,
  "exori-hur": 18,
  "exori-ico": 22,
  "exori-infir-con": 159,
  "exori-infir-min": 160,
  "exori-infir-tera": 136,
  "exori-infir-vis": 132,
  "exori-mas": 24,
  "exori-max-flam": 27,
  "exori-max-frigo": 33,
  "exori-max-tera": 36,
  "exori-max-vis": 30,
  "exori-min": 19,
  "exori-min-flam": 126,
  "exori-moe-ico": 16,
  "exori-mort": 37,
  "exori-san": 38,
  "exori-tera": 34,
  "exori-vis": 28,
  "explosion-rune": 82,
  "exura": 5,
  "exura-dis": 127,
  "exura-gran": 6,
  "exura-gran-ico": 3,
  "exura-gran-san": 59,
  "exura-gran-sio": 106,
  "exura-gran-tio": 161,
  "exura-ico": 2,
  "exura-infir": 133,
  "exura-infir-ico": 134,
  "exura-max-vita": 107,
  "exura-med-ico": 4,
  "exura-san": 1,
  "exura-sio": 7,
  "exura-tio-sio": 185,
  "exura-vita": 0,
  "fireball-rune": 78,
  "great-fireball-rune": 77,
  "heavy-magic-missile-rune": 76,
  "holy-missile-rune": 75,
  "icicle-rune": 74,
  "intense-healing-rune": 73,
  "light-magic-missile-rune": 72,
  "lightest-magic-missile-rune": 72,
  "lightest-missile-rune": 72,
  "paralyze-rune": 70,
  "soulfire-rune": 66,
  "stalagmite-rune": 65,
  "stone-shower-rune": 64,
  "sudden-death-rune": 63,
  "thunderstorm-rune": 62,
  "ultimate-healing-rune": 61,
  "utamo-vita": 123,
  "utana-vid": 93,
  "utani-gran-hur": 101,
  "utani-hur": 100,
  "utevo-gran-lux": 115,
  "utevo-lux": 116,
  "utevo-vis-lux": 114,
  "utori-flam": 54,
  "utori-kor": 56,
  "utori-mort": 53,
  "utori-pox": 57,
  "utori-vis": 55,
  "utura": 14,
  "utura-gran": 15,
};

const LEGACY_SPELL_ICON_INDEXES: Readonly<Record<string, number>> = {
  "exevo-con-grav": 109,
  "exevo-con-hur": 111,
  "exevo-con-mort": 106,
  "exevo-con-pox": 110,
  "exevo-con-vis": 107,
};

export function getSpellIconArtwork(
  spellId: string,
): SpellIconArtwork | undefined {
  const currentIndex = CURRENT_SPELL_ICON_INDEXES[spellId];
  if (currentIndex !== undefined) {
    return { sheet: "current", index: currentIndex };
  }

  const legacyIndex = LEGACY_SPELL_ICON_INDEXES[spellId];
  if (legacyIndex !== undefined) {
    return { sheet: "legacy", index: legacyIndex };
  }

  return undefined;
}
