import { SPELL_ARTWORK_BY_EFFECT } from "./spellArtwork";
import type { SpellListSpell } from "./spellTypes";

// Display metadata sourced from Canary commit a879c9312e34381e8eedf397b8ed44510698b689.
export const KNIGHT_SPELLS = [
  {
    id: "healing-bruise_bane",
    name: "Bruise Bane",
    words: "exura infir ico",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 1,
    manaCost: 10,
  },
  {
    id: "attack-lesser_front_sweep",
    name: "Lesser Front Sweep",
    words: "exori infir min",
    artwork: SPELL_ARTWORK_BY_EFFECT[10],
    requiredLevel: 1,
    manaCost: 6,
  },
  {
    id: "support-find_person",
    name: "Find Person",
    words: "exiva",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 8,
    manaCost: 20,
  },
  {
    id: "house-house_door_list",
    name: "House Door List",
    words: "aleta grav",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 8,
    manaCost: 0,
  },
  {
    id: "house-house_guest_list",
    name: "House Guest List",
    words: "aleta sio",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 8,
    manaCost: 0,
  },
  {
    id: "house-house_kick",
    name: "House Kick",
    words: "alana sio",
    artwork: SPELL_ARTWORK_BY_EFFECT[11],
    requiredLevel: 8,
    manaCost: 0,
  },
  {
    id: "house-house_subowner_list",
    name: "House Subowner List",
    words: "aleta som",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 8,
    manaCost: 0,
  },
  {
    id: "support-light",
    name: "Light",
    words: "utevo lux",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 8,
    manaCost: 20,
  },
  {
    id: "healing-wound_cleansing",
    name: "Wound Cleansing",
    words: "exura ico",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 8,
    manaCost: 40,
  },
  {
    id: "support-magic_rope",
    name: "Magic Rope",
    words: "exani tera",
    artwork: SPELL_ARTWORK_BY_EFFECT[11],
    requiredLevel: 9,
    manaCost: 20,
  },
  {
    id: "healing-cure_poison",
    name: "Cure Poison",
    words: "exana pox",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 10,
    manaCost: 30,
  },
  {
    id: "support-levitate",
    name: "Levitate",
    words: "exani hur",
    artwork: SPELL_ARTWORK_BY_EFFECT[11],
    requiredLevel: 12,
    manaCost: 50,
  },
  {
    id: "support-great_light",
    name: "Great Light",
    words: "utevo gran lux",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 13,
    manaCost: 60,
  },
  {
    id: "support-haste",
    name: "Haste",
    words: "utani hur",
    artwork: SPELL_ARTWORK_BY_EFFECT[15],
    requiredLevel: 14,
    manaCost: 60,
  },
  {
    id: "attack-brutal_strike",
    name: "Brutal Strike",
    words: "exori ico",
    artwork: SPELL_ARTWORK_BY_EFFECT[10],
    requiredLevel: 16,
    manaCost: 30,
  },
  {
    id: "support-challenge",
    name: "Challenge",
    words: "exeta res",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 20,
    manaCost: 30,
  },
  {
    id: "support-charge",
    name: "Charge",
    words: "utani tempo hur",
    artwork: SPELL_ARTWORK_BY_EFFECT[15],
    requiredLevel: 25,
    manaCost: 100,
  },
  {
    id: "support-find_fiend",
    name: "Find Fiend",
    words: "exiva moe res",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 25,
    manaCost: 20,
  },
  {
    id: "attack-whirlwind_throw",
    name: "Whirlwind Throw",
    words: "exori hur",
    artwork: SPELL_ARTWORK_BY_EFFECT[10],
    requiredLevel: 28,
    manaCost: 40,
  },
  {
    id: "party-train_party",
    name: "Train Party",
    words: "utito mas sio",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 32,
    manaCost: 60,
  },
  {
    id: "attack-groundshaker",
    name: "Groundshaker",
    words: "exori mas",
    artwork: SPELL_ARTWORK_BY_EFFECT[35],
    requiredLevel: 33,
    manaCost: 160,
  },
  {
    id: "attack-berserk",
    name: "Berserk",
    words: "exori",
    artwork: SPELL_ARTWORK_BY_EFFECT[10],
    requiredLevel: 35,
    manaCost: 115,
  },
  {
    id: "attack-inflict_wound",
    name: "Inflict Wound",
    words: "utori kor",
    artwork: SPELL_ARTWORK_BY_EFFECT[1],
    requiredLevel: 40,
    manaCost: 30,
  },
  {
    id: "healing-cure_bleeding",
    name: "Cure Bleeding",
    words: "exana kor",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 45,
    manaCost: 30,
  },
  {
    id: "healing-recovery",
    name: "Recovery",
    words: "utura",
    artwork: SPELL_ARTWORK_BY_EFFECT[15],
    requiredLevel: 50,
    manaCost: 75,
  },
  {
    id: "support-protector",
    name: "Protector",
    words: "utamo tempo",
    artwork: SPELL_ARTWORK_BY_EFFECT[15],
    requiredLevel: 55,
    manaCost: 200,
  },
  {
    id: "support-blood_rage",
    name: "Blood Rage",
    words: "utito tempo",
    artwork: SPELL_ARTWORK_BY_EFFECT[15],
    requiredLevel: 60,
    manaCost: 290,
  },
  {
    id: "attack-front_sweep",
    name: "Front Sweep",
    words: "exori min",
    artwork: SPELL_ARTWORK_BY_EFFECT[10],
    requiredLevel: 70,
    manaCost: 200,
  },
  {
    id: "healing-intense_wound_cleansing",
    name: "Intense Wound Cleansing",
    words: "exura gran ico",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 80,
    manaCost: 200,
  },
  {
    id: "attack-fierce_berserk",
    name: "Fierce Berserk",
    words: "exori gran",
    artwork: SPELL_ARTWORK_BY_EFFECT[10],
    requiredLevel: 90,
    manaCost: 340,
  },
  {
    id: "healing-intense_recovery",
    name: "Intense Recovery",
    words: "utura gran",
    artwork: SPELL_ARTWORK_BY_EFFECT[15],
    requiredLevel: 100,
    manaCost: 165,
  },
  {
    id: "attack-annihilation",
    name: "Annihilation",
    words: "exori gran ico",
    artwork: SPELL_ARTWORK_BY_EFFECT[10],
    requiredLevel: 110,
    manaCost: 300,
  },
  {
    id: "support-chivalrous_challenge",
    name: "Chivalrous Challenge",
    words: "exeta amp res",
    artwork: SPELL_ARTWORK_BY_EFFECT[219],
    requiredLevel: 150,
    manaCost: 80,
  },
  {
    id: "familiar-knight_familiar",
    name: "Knight familiar",
    words: "utevo gran res eq",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 200,
    manaCost: 1000,
  },
  {
    id: "support-avatar_of_steel",
    name: "Avatar of Steel",
    words: "uteta res eq",
    artwork: SPELL_ARTWORK_BY_EFFECT[244],
    requiredLevel: 300,
    manaCost: 800,
  },
  {
    id: "attack-executioners_throw",
    name: "Executioner's Throw",
    words: "exori amp kor",
    artwork: SPELL_ARTWORK_BY_EFFECT[10],
    requiredLevel: 300,
    manaCost: 225,
  },
  {
    id: "healing-fair_wound_cleansing",
    name: "Fair Wound Cleansing",
    words: "exura med ico",
    artwork: SPELL_ARTWORK_BY_EFFECT[13],
    requiredLevel: 300,
    manaCost: 90,
  },
] as const satisfies ReadonlyArray<SpellListSpell>;
