import type { ItemTooltipData } from "@tibia/protocol";

// Display-only mock items until item stats/rarities exist server-side.
// spriteIds are sprites[0] of the named clientIds, visually verified.
export const PLACEHOLDER_TOOLTIP_ITEMS = {
  sword: {
    name: "Emberfang, Blade of the Molten King",
    rarity: "legendary",
    typeLine: "Ancestral Legendary Sword",
    spriteId: 7749,
    primaryStat: "48 Attack",
    affixes: [
      { text: "+12.0% Attack Speed", range: "[8.4 - 12.6]%" },
      { text: "+9.6% Critical Strike Chance", range: "[5.2 - 9.6]%" },
      { text: "+184 Strength", range: "[95 - 210]" },
      { text: "+2 to Sword Mastery" },
    ],
    requiredLevel: 68,
    accountBound: true,
    sellValue: 24310,
    durability: { current: 100, max: 100 },
  },
  axe: {
    name: "Oathbreaker's Cleaver",
    rarity: "epic",
    typeLine: "Epic Battle Axe",
    spriteId: 7735,
    primaryStat: "41 Attack",
    affixes: [
      { text: "+15.2% Overpower Damage", range: "[9.8 - 16.4]%" },
      { text: "+11% Damage to Slowed Enemies", range: "[8 - 14]%" },
      { text: "+96 Strength", range: "[55 - 120]" },
    ],
    requiredLevel: 61,
    sellValue: 9845,
    durability: { current: 84, max: 100 },
  },
  club: {
    name: "Morning Star",
    rarity: "common",
    typeLine: "Common Club",
    spriteId: 7752,
    primaryStat: "25 Attack",
    affixes: [],
    requiredLevel: 20,
    sellValue: 320,
    durability: { current: 45, max: 50 },
  },
  bow: {
    name: "Whisperwind Longbow",
    rarity: "rare",
    typeLine: "Rare Bow",
    spriteId: 7836,
    primaryStat: "38 Attack",
    affixes: [
      { text: "+11.4% Ranged Critical Strike Chance", range: "[6.0 - 11.4]%" },
      { text: "+9% Movement Speed for 4s After a Kill", range: "[6 - 12]%" },
      { text: "+37 Dexterity", range: "[22 - 48]" },
    ],
    requiredLevel: 44,
    sellValue: 4210,
    durability: { current: 92, max: 100 },
  },
  crossbow: {
    name: "Ironbolt Arbalest",
    rarity: "uncommon",
    typeLine: "Uncommon Crossbow",
    spriteId: 7835,
    primaryStat: "33 Attack",
    affixes: [
      { text: "+8.5% Attack Speed", range: "[6.2 - 10.0]%" },
      { text: "+22 Dexterity", range: "[14 - 30]" },
    ],
    requiredLevel: 30,
    sellValue: 1150,
    durability: { current: 61, max: 80 },
  },
  wand: {
    name: "Wand of the Hollow Vortex",
    rarity: "legendary",
    typeLine: "Ancestral Legendary Wand",
    spriteId: 7503,
    primaryStat: "36 Attack",
    affixes: [
      { text: "+14.5% Energy Damage", range: "[9.0 - 15.5]%" },
      { text: "+310 Maximum Mana", range: "[180 - 340]" },
      { text: "+7.2% Cooldown Reduction", range: "[4.0 - 8.0]%" },
      { text: "+3 to Vortex Spells" },
    ],
    requiredLevel: 70,
    accountBound: true,
    sellValue: 27980,
    durability: { current: 100, max: 100 },
  },
  shield: {
    name: "Bulwark of the Deep Mountain",
    rarity: "epic",
    typeLine: "Epic Tower Shield",
    spriteId: 7917,
    primaryStat: "34 Defense",
    affixes: [
      { text: "+18.0% Block Chance", range: "[12.0 - 18.0]%" },
      { text: "+322 Maximum Life", range: "[190 - 360]" },
      { text: "Thorns: reflect 145 damage to melee attackers", range: "[90 - 170]" },
      { text: "+6.0% Total Armor", range: "[3.5 - 7.0]%" },
    ],
    requiredLevel: 55,
    sellValue: 12400,
    durability: { current: 77, max: 100 },
  },
  helmet: {
    name: "Doom Casque of the Protector",
    rarity: "legendary",
    typeLine: "Sacred Legendary Helm",
    spriteId: 7837,
    primaryStat: "12 Armor",
    affixes: [
      { text: "9.6% Cooldown Reduction", range: "[4.5 - 9.6]%" },
      { text: "+461 Maximum Life", range: "[218 - 461]" },
      { text: "+3.5% Total Armor", range: "[2.7 - 6.6]%" },
      { text: "+4.5% Basic Skill Attack Speed", range: "[4.5 - 9.8]%" },
    ],
    requiredLevel: 71,
    accountBound: true,
    sellValue: 30008,
    durability: { current: 90, max: 100 },
  },
  armor: {
    name: "Aegis of Withered Kings",
    rarity: "rare",
    typeLine: "Rare Plate Armor",
    spriteId: 7843,
    primaryStat: "17 Armor",
    affixes: [
      { text: "+288 Maximum Life", range: "[160 - 320]" },
      { text: "+12% Fire Resistance", range: "[8 - 16]%" },
      { text: "+9.5% Damage Reduction While Injured", range: "[6.0 - 11.0]%" },
    ],
    requiredLevel: 49,
    sellValue: 6730,
    durability: { current: 68, max: 100 },
  },
  legs: {
    name: "Greaves of the Silent March",
    rarity: "uncommon",
    typeLine: "Uncommon Plate Legs",
    spriteId: 8141,
    primaryStat: "9 Armor",
    affixes: [
      { text: "+140 Maximum Life", range: "[85 - 165]" },
      { text: "+5% Dodge Chance", range: "[3 - 7]%" },
    ],
    requiredLevel: 33,
    sellValue: 1490,
    durability: { current: 100, max: 100 },
  },
  boots: {
    name: "Boots of Haste",
    rarity: "epic",
    typeLine: "Epic Boots",
    spriteId: 7517,
    primaryStat: "4 Armor",
    affixes: [
      { text: "+22% Movement Speed", range: "[15 - 25]%" },
      { text: "+3.8% Attack Speed", range: "[2.5 - 5.0]%" },
      { text: "+64 Dexterity", range: "[40 - 75]" },
    ],
    requiredLevel: 52,
    accountBound: true,
    sellValue: 15220,
    durability: { current: 96, max: 100 },
  },
  ring: {
    name: "Band of the Prudent",
    rarity: "rare",
    typeLine: "Rare Gold Ring",
    spriteId: 7338,
    primaryStat: undefined,
    affixes: [
      { text: "+8% All Resistances", range: "[5 - 10]%" },
      { text: "+190 Maximum Mana", range: "[110 - 220]" },
      { text: "+6.4% Lucky Hit Chance", range: "[4.0 - 8.0]%" },
    ],
    requiredLevel: 41,
    sellValue: 5340,
  },
  amulet: {
    name: "Platinum Sigil of Warding",
    rarity: "legendary",
    typeLine: "Sacred Legendary Amulet",
    spriteId: 7461,
    affixes: [
      { text: "+19% Cold Resistance", range: "[12 - 22]%" },
      { text: "+11.5% Total Armor", range: "[7.0 - 12.5]%" },
      { text: "+2 to Defensive Skills" },
    ],
    requiredLevel: 66,
    accountBound: true,
    sellValue: 22150,
  },
} satisfies Readonly<Record<string, ItemTooltipData>>;
