import type { ItemTooltipData } from "@tibia/protocol";

export const TIBIA_TOOLTIP_ITEMS = {
  sword: {
    name: "Sabre",
    typeLine: "Sword Weapons",
    spriteId: 7742,
    primaryStat: "Attack 12 · Defense 10",
    affixes: [{ text: "Extra Defense +1" }],
    weight: 2500,
  },
  axe: {
    name: "Axe",
    typeLine: "Axe Weapons",
    spriteId: 7743,
    primaryStat: "Attack 12 · Defense 6",
    affixes: [],
    weight: 4000,
  },
  club: {
    name: "Club",
    typeLine: "Club Weapons",
    spriteId: 7739,
    primaryStat: "Attack 7 · Defense 7",
    affixes: [],
    weight: 2500,
  },
  bow: {
    name: "Bow",
    typeLine: "Distance Weapons",
    spriteId: 7836,
    affixes: [{ text: "Range 6" }],
    weight: 3100,
  },
  crossbow: {
    name: "Crossbow",
    typeLine: "Distance Weapons",
    spriteId: 7835,
    affixes: [{ text: "Range 5" }, { text: "Imbuement Slots 3" }],
    weight: 4000,
  },
  wand: {
    name: "Wand Of Vortex",
    typeLine: "Wands",
    spriteId: 7503,
    primaryStat: "Damage 8-18",
    affixes: [
      { text: "Range 3" },
      { text: "Mana Cost 1" },
      { text: "Energy Damage" },
    ],
    requiredLevel: 6,
    vocations: ["Sorcerer", "Master Sorcerer"],
    description: "Surges of energy rush through the tip of this wand",
    weight: 1900,
  },
  shield: {
    name: "Wooden Shield",
    typeLine: "Shields",
    spriteId: 7898,
    primaryStat: "Defense 14",
    affixes: [],
    weight: 4000,
  },
  helmet: {
    name: "Leather Helmet",
    typeLine: "Helmets",
    spriteId: 7841,
    primaryStat: "Armor 1",
    affixes: [],
    weight: 2200,
  },
  armor: {
    name: "Leather Armor",
    typeLine: "Armors",
    spriteId: 7847,
    primaryStat: "Armor 4",
    affixes: [],
    weight: 6000,
  },
  legs: {
    name: "Studded Legs",
    typeLine: "Legs",
    spriteId: 7848,
    primaryStat: "Armor 2",
    affixes: [],
    weight: 2600,
  },
  boots: {
    name: "Leather Boots",
    typeLine: "Boots",
    spriteId: 8125,
    primaryStat: "Armor 1",
    affixes: [{ text: "Imbuement Slots 1" }],
    weight: 900,
  },
  ring: {
    name: "Gold Ring",
    typeLine: "Rings",
    spriteId: 7468,
    affixes: [],
    weight: 100,
  },
  amulet: {
    name: "Protection Amulet",
    typeLine: "Amulets And Necklaces",
    spriteId: 7522,
    affixes: [{ text: "Physical Protection +6%" }],
    charges: 250,
    weight: 550,
  },
} satisfies Readonly<Record<string, ItemTooltipData>>;
