import type { ItemTooltipData } from "@tibia/protocol";

export const TIBIA_TOOLTIP_ITEMS = {
  sword: {
    name: "Sabre",
    typeLine: "Sword Weapons",
    spriteId: 7742,
    rarity: "common",
    primaryStat: "Attack 12 · Defense 10",
    affixes: [{ text: "Extra Defense +1" }],
    weight: 2500,
  },
  axe: {
    name: "Axe",
    typeLine: "Axe Weapons",
    spriteId: 7743,
    rarity: "common",
    primaryStat: "Attack 12 · Defense 6",
    affixes: [],
    weight: 4000,
  },
  club: {
    name: "Club",
    typeLine: "Club Weapons",
    spriteId: 7739,
    rarity: "common",
    primaryStat: "Attack 7 · Defense 7",
    affixes: [],
    weight: 2500,
  },
  bow: {
    name: "Bow",
    typeLine: "Distance Weapons",
    spriteId: 7836,
    rarity: "common",
    affixes: [{ text: "Range 6" }],
    weight: 3100,
  },
  crossbow: {
    name: "Crossbow",
    typeLine: "Distance Weapons",
    spriteId: 7835,
    rarity: "common",
    affixes: [
      { text: "Range 5" },
      {
        text: "Imbuements: (Empty Slot, Empty Slot, Empty Slot)",
        kind: "imbuement",
      },
    ],
    weight: 4000,
    worth: 120,
    imbuementSlots: 3,
  },
  wand: {
    name: "Wand Of Vortex",
    typeLine: "Wands",
    spriteId: 7503,
    rarity: "common",
    primaryStat: "Damage 8-18",
    affixes: [
      { text: "Range 3" },
      { text: "Mana Cost 1" },
      { text: "Energy Damage" },
    ],
    requiredLevel: 6,
    vocations: ["Sorcerer", "Master Sorcerer"],
    description: "Surges of energy rush through the tip of this wand",
    weight: 1900,
  },
  shield: {
    name: "Wooden Shield",
    typeLine: "Shields",
    spriteId: 7898,
    rarity: "common",
    primaryStat: "Defense 14",
    affixes: [],
    weight: 4000,
  },
  helmet: {
    name: "Leather Helmet",
    typeLine: "Helmets",
    spriteId: 7841,
    rarity: "common",
    primaryStat: "Armor 1",
    affixes: [],
    weight: 2200,
  },
  armor: {
    name: "Leather Armor",
    typeLine: "Armors",
    spriteId: 7847,
    rarity: "common",
    primaryStat: "Armor 4",
    affixes: [],
    weight: 6000,
  },
  legs: {
    name: "Studded Legs",
    typeLine: "Legs",
    spriteId: 7848,
    rarity: "common",
    primaryStat: "Armor 2",
    affixes: [],
    weight: 2600,
  },
  boots: {
    name: "Leather Boots",
    typeLine: "Boots",
    spriteId: 8125,
    rarity: "common",
    primaryStat: "Armor 1",
    affixes: [{ text: "Imbuements: (Empty Slot)", kind: "imbuement" }],
    weight: 900,
    worth: 2,
    imbuementSlots: 1,
  },
  ring: {
    name: "Gold Ring",
    typeLine: "Rings",
    spriteId: 7468,
    rarity: "common",
    affixes: [],
    weight: 100,
  },
  amulet: {
    name: "Protection Amulet",
    typeLine: "Amulets And Necklaces",
    spriteId: 7522,
    rarity: "common",
    affixes: [{ text: "Physical Protection +6%" }],
    charges: 250,
    weight: 550,
  },
  uncommonWand: {
    name: "Wand Of Draconia",
    typeLine: "Wands",
    spriteId: 7503,
    rarity: "uncommon",
    primaryStat: "Damage 19-31",
    affixes: [
      { text: "+37 Maximum Mana", kind: "rolled" },
      { text: "Range 3" },
      { text: "Fire Damage" },
      { text: "Imbuements: (Empty Slot, Empty Slot)", kind: "imbuement" },
    ],
    requiredLevel: 22,
    vocations: ["Sorcerer"],
    description: "This wand holds the spirit and soul of a dragon lord.",
    weight: 2700,
    worth: 1500,
    imbuementSlots: 2,
  },
  rareSword: {
    name: "Fire Sword",
    typeLine: "Sword Weapons",
    spriteId: 7742,
    rarity: "rare",
    primaryStat: "Attack 24 · Defense 20",
    affixes: [
      { text: "+4 Attack", kind: "rolled" },
      { text: "+3% Life Leech", kind: "rolled" },
      { text: "Extra Defense +1" },
      {
        text: "Imbuements: (Powerful Scorch 19:58h, Empty Slot)",
        kind: "imbuement",
      },
    ],
    requiredLevel: 30,
    weight: 2300,
    worth: 4000,
    imbuementSlots: 2,
  },
  epicArmor: {
    name: "Knight Armor",
    typeLine: "Armors",
    spriteId: 7847,
    rarity: "epic",
    primaryStat: "Armor 12",
    affixes: [
      { text: "+68 Maximum Health", kind: "rolled" },
      { text: "+7 Defense", kind: "rolled" },
      { text: "+11% Fire Resistance", kind: "rolled" },
      { text: "Imbuements: (Empty Slot, Empty Slot)", kind: "imbuement" },
    ],
    requiredLevel: 25,
    vocations: ["Knight", "Paladin"],
    weight: 12000,
    worth: 5000,
    imbuementSlots: 2,
  },
  legendaryHelmet: {
    name: "Crusader Helmet",
    typeLine: "Helmets",
    spriteId: 7841,
    rarity: "legendary",
    primaryStat: "Armor 9",
    affixes: [
      { text: "+117 Maximum Health", kind: "rolled" },
      { text: "+9% Attack Speed", kind: "rolled" },
      { text: "+6% Critical Hit Chance", kind: "rolled" },
      { text: "+3 Magic Level", kind: "rolled" },
      { text: "Imbuements: (Empty Slot)", kind: "imbuement" },
    ],
    requiredLevel: 50,
    description: "Worn by the champions of forgotten crusades.",
    weight: 2900,
    worth: 6000,
    imbuementSlots: 1,
  },
} satisfies Readonly<Record<string, ItemTooltipData>>;
