import type { SpellDefinition } from "../../Spell";

export const exanaVita: SpellDefinition = {
  id: "exana-vita",
  numericId: 245,
  sourcePath: "data/scripts/spells/support/cancel_magic_shield.lua",
  name: "Cancel Magic Shield",
  words: "exana vita",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Sorcerer", "Elder Druid", "Master Sorcerer"],
  requiredLevel: 14,
  requiredMagicLevel: 0,
  manaCost: 50,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "magic-shield",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
