import type { SpellDefinition } from "../../Spell";

export const exanaAmpRes: SpellDefinition = {
  id: "exana-amp-res",
  numericId: 238,
  sourcePath: "data/scripts/spells/support/divine_dazzle.lua",
  name: "Divine Dazzle",
  words: "exana amp res",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 250,
  requiredMagicLevel: 0,
  manaCost: 80,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 16_000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 220,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: "divine-dazzle",
  wheelRevelation: null,
};
