import type { SpellDefinition } from "../../Spell";

export const exaniHur: SpellDefinition = {
  id: "exani-hur",
  numericId: 81,
  sourcePath: "data/scripts/spells/support/levitate.lua",
  name: "Levitate",
  words: "exani hur",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: [
    "Druid",
    "Elder Druid",
    "Knight",
    "Elite Knight",
    "Paladin",
    "Royal Paladin",
    "Sorcerer",
    "Master Sorcerer",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 12,
  requiredMagicLevel: 0,
  manaCost: 50,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 11,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: "levitate",
  playerAction: null,
  wheelRevelation: null,
};
