import type { SpellDefinition } from "../../Spell";

export const exetaAmpRes: SpellDefinition = {
  id: "exeta-amp-res",
  numericId: 237,
  sourcePath: "data/scripts/spells/support/chivalrous_challenge.lua",
  name: "Chivalrous Challenge",
  words: "exeta amp res",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 150,
  requiredMagicLevel: 0,
  manaCost: 80,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 219,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: "chivalrous-challenge",
  wheelRevelation: null,
};
