import type { SpellDefinition } from "../../Spell";

export const exetaRes: SpellDefinition = {
  id: "exeta-res",
  numericId: 93,
  sourcePath: "data/scripts/spells/support/challenge.lua",
  name: "Challenge",
  words: "exeta res",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Elite Knight"],
  requiredLevel: 20,
  requiredMagicLevel: 0,
  manaCost: 30,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [
      { x: -1, y: -1 },
      { x: 0, y: -1 },
      { x: 1, y: -1 },
      { x: -1, y: 0 },
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: -1, y: 1 },
      { x: 0, y: 1 },
      { x: 1, y: 1 },
    ],
    directional: false,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: "challenge",
  wheelRevelation: null,
};
