import type { SpellDefinition } from "../../Spell";

export const exevoPan: SpellDefinition = {
  id: "exevo-pan",
  numericId: 42,
  sourcePath: "data/scripts/spells/support/food.lua",
  name: "Food",
  words: "exevo pan",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 14,
  requiredMagicLevel: 0,
  manaCost: 120,
  soulCost: 1,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 15,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: "conjure-random-food",
  wheelRevelation: null,
};
