import type { SpellDefinition } from "../../Spell";

export const exoriMasRes: SpellDefinition = {
  id: "exori-mas-res",
  numericId: 280,
  sourcePath: "data/scripts/spells/support/balanced_brawl.lua",
  name: "Balanced Brawl",
  words: "exori mas res",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Monk", "Exalted Monk"],
  requiredLevel: 175,
  requiredMagicLevel: 0,
  manaCost: 80,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 10_000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: true,
  targetKind: "direction",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [
      { x: 0, y: -5 },
      { x: -2, y: -4 },
      { x: -1, y: -4 },
      { x: 0, y: -4 },
      { x: 1, y: -4 },
      { x: 2, y: -4 },
      { x: -3, y: -3 },
      { x: -2, y: -3 },
      { x: -1, y: -3 },
      { x: 0, y: -3 },
      { x: 1, y: -3 },
      { x: 2, y: -3 },
      { x: 3, y: -3 },
      { x: -4, y: -2 },
      { x: -3, y: -2 },
      { x: -2, y: -2 },
      { x: -1, y: -2 },
      { x: 0, y: -2 },
      { x: 1, y: -2 },
      { x: 2, y: -2 },
      { x: 3, y: -2 },
      { x: 4, y: -2 },
      { x: -5, y: -1 },
      { x: -4, y: -1 },
      { x: -3, y: -1 },
      { x: -2, y: -1 },
      { x: -1, y: -1 },
      { x: 0, y: -1 },
      { x: 1, y: -1 },
      { x: 2, y: -1 },
      { x: 3, y: -1 },
      { x: 4, y: -1 },
      { x: 5, y: -1 },
      { x: -5, y: 0 },
      { x: -4, y: 0 },
      { x: -3, y: 0 },
      { x: -2, y: 0 },
      { x: 2, y: 0 },
      { x: 3, y: 0 },
      { x: 4, y: 0 },
      { x: 5, y: 0 },
      { x: -6, y: 1 },
      { x: -5, y: 1 },
      { x: -4, y: 1 },
      { x: -3, y: 1 },
      { x: -2, y: 1 },
      { x: 2, y: 1 },
      { x: 3, y: 1 },
      { x: 4, y: 1 },
      { x: 5, y: 1 },
      { x: 6, y: 1 },
    ],
    directional: true,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: "balanced-brawl",
  wheelRevelation: null,
};
