import type { SpellDefinition } from "../../Spell";

export const utamoVita: SpellDefinition = {
  id: "utamo-vita",
  numericId: 44,
  sourcePath: "data/scripts/spells/support/magic_shield.lua",
  name: "Magic Shield",
  words: "utamo vita",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid", "Sorcerer", "Master Sorcerer"],
  requiredLevel: 14,
  requiredMagicLevel: 0,
  manaCost: 50,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 14_000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "magic-shield",
    durationMs: 180_000,
    magicShieldFormula: { base: 300, level: 7.6, magicLevel: 7 },
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
