import type { SpellDefinition } from "../../Spell";

export const utamoTempo: SpellDefinition = {
  id: "utamo-tempo",
  numericId: 132,
  sourcePath: "data/scripts/spells/support/protector.lua",
  name: "Protector",
  words: "utamo tempo",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 55,
  requiredMagicLevel: 0,
  manaCost: 200,
  soulCost: 0,
  groups: ["support", "focus"],
  cooldownMs: 2000,
  groupCooldownMs: [2000, 2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 15,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "attributes",
    durationMs: 13_000,
    defensePercent: 220,
    damageDealtPercent: 65,
    damageReceivedPercent: 85,
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
