import type { SpellDefinition } from "../../Spell";

export const utaniGranHur: SpellDefinition = {
  id: "utani-gran-hur",
  numericId: 39,
  sourcePath: "data/scripts/spells/support/strong_haste.lua",
  name: "Strong Haste",
  words: "utani gran hur",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: [
    "Druid",
    "Elder Druid",
    "Sorcerer",
    "Master Sorcerer",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 20,
  requiredMagicLevel: 0,
  manaCost: 100,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 15,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "haste",
    durationMs: 22_000,
    speedFormula: { coefficient: 1.7, base: 40 },
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
