import type { SpellDefinition } from "../../Spell";

export const utaniHur: SpellDefinition = {
  id: "utani-hur",
  numericId: 6,
  sourcePath: "data/scripts/spells/support/haste.lua",
  name: "Haste",
  words: "utani hur",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: [
    "Druid",
    "Elder Druid",
    "Knight",
    "Elite Knight",
    "Paladin",
    "Royal Paladin",
    "Sorcerer",
    "Master Sorcerer",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 14,
  requiredMagicLevel: 0,
  manaCost: 60,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 15,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "haste",
    durationMs: 30_000,
    speedFormula: { coefficient: 1.3, base: 40 },
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
