import type { SpellDefinition } from "../../Spell";

export const utanaVid: SpellDefinition = {
  id: "utana-vid",
  numericId: 45,
  sourcePath: "data/scripts/spells/support/invisible.lua",
  name: "Invisibility",
  words: "utana vid",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid", "Sorcerer", "Master Sorcerer"],
  requiredLevel: 35,
  requiredMagicLevel: 0,
  manaCost: 440,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: { type: "invisible", durationMs: 200_000 },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
