import type { SpellDefinition } from "../../Spell";

export const utaniTempoHur: SpellDefinition = {
  id: "utani-tempo-hur",
  numericId: 131,
  sourcePath: "data/scripts/spells/support/charge.lua",
  name: "Charge",
  words: "utani tempo hur",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 25,
  requiredMagicLevel: 0,
  manaCost: 100,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 15,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "haste",
    durationMs: 5000,
    speedFormula: { coefficient: 1.9, base: 40 },
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
