import type { SpellDefinition } from "../../Spell";

export const utetaTio: SpellDefinition = {
  id: "uteta-tio",
  numericId: 277,
  sourcePath: "data/scripts/spells/support/mentor_other.lua",
  name: "Mentor Other",
  words: "uteta tio",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Monk", "Exalted Monk"],
  requiredLevel: 150,
  requiredMagicLevel: 0,
  manaCost: 110,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 50_000,
  groupCooldownMs: [2000],
  range: 7,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: "mentor-other",
  wheelRevelation: null,
};
