import type { SpellDefinition } from "../../Spell";

/** Paladin purple revelation: 15 s as lookType 1594 (see uteta-res-eq). */
export const utetaResSac: SpellDefinition = {
  id: "uteta-res-sac",
  numericId: 265,
  sourcePath: "data/scripts/spells/support/avatar_of_light.lua",
  name: "Avatar of Light",
  words: "uteta res sac",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 300,
  requiredMagicLevel: 0,
  manaCost: 1500,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 7_200_000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 244,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: "avatar",
  wheelRevelation: { domain: "purple", minimumStage: 1 },
};
