import type { SpellDefinition } from "../../Spell";

export const utevoVisLux: SpellDefinition = {
  id: "utevo-vis-lux",
  numericId: 75,
  sourcePath: "data/scripts/spells/support/ultimate_light.lua",
  name: "Ultimate Light",
  words: "utevo vis lux",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid", "Sorcerer", "Master Sorcerer"],
  requiredLevel: 26,
  requiredMagicLevel: 0,
  manaCost: 140,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "light",
    durationMs: 1_990_000,
    light: { intensity: 8, color: 215 },
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
