import type { SpellDefinition } from "../../Spell";

export const utevoRes: SpellDefinition = {
  id: "utevo-res",
  numericId: 9,
  sourcePath: "data/scripts/spells/support/summon_creature.lua",
  name: "Summon Creature",
  words: "utevo res",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Sorcerer", "Elder Druid", "Master Sorcerer"],
  requiredLevel: 25,
  requiredMagicLevel: 0,
  manaCost: 0,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: "summon-creature",
  wheelRevelation: null,
};
