import type { SpellDefinition } from "../../Spell";

export const utevoGranLux: SpellDefinition = {
  id: "utevo-gran-lux",
  numericId: 11,
  sourcePath: "data/scripts/spells/support/great_light.lua",
  name: "Great Light",
  words: "utevo gran lux",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: [
    "Druid",
    "Elder Druid",
    "Knight",
    "Elite Knight",
    "Paladin",
    "Royal Paladin",
    "Sorcerer",
    "Master Sorcerer",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 13,
  requiredMagicLevel: 0,
  manaCost: 60,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "light",
    durationMs: 695_000,
    light: { intensity: 8, color: 215 },
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
