import type { SpellDefinition } from "../../Spell";

export const utevoResIna: SpellDefinition = {
  id: "utevo-res-ina",
  numericId: 38,
  sourcePath: "data/scripts/spells/support/creature_illusion.lua",
  name: "Creature Illusion",
  words: "utevo res ina",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid", "Sorcerer", "Master Sorcerer"],
  requiredLevel: 23,
  requiredMagicLevel: 0,
  manaCost: 100,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 14,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: "creature-illusion",
  wheelRevelation: null,
};
