import type { SpellDefinition } from "../../Spell";

export const utitoTempo: SpellDefinition = {
  id: "utito-tempo",
  numericId: 133,
  sourcePath: "data/scripts/spells/support/blood_rage.lua",
  name: "Blood Rage",
  words: "utito tempo",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 60,
  requiredMagicLevel: 0,
  manaCost: 290,
  soulCost: 0,
  groups: ["support", "focus"],
  cooldownMs: 2000,
  groupCooldownMs: [2000, 2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 15,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "attributes",
    durationMs: 10_000,
    meleePercent: 135,
    damageReceivedPercent: 115,
    disablesDefense: true,
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
