import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const CONTENT_DIR =
  process.env.CONTENT_DIR ??
  fileURLToPath(new URL("../../../content", import.meta.url));
const STORAGE_KEY = /^[A-Za-z0-9_:.-]+$/;

export interface QuestStorageAliases {
  /** Alias key -> canonical key; identity for unknown keys. */
  canonicalOf(key: string): string;
  readonly size: number;
}

/**
 * Canary aliases several `Storage.*` names onto one numeric storage id;
 * aliased keys must share one row (Feature 103). The map is generated by
 * the Feature 105 parity tool; until it ships, an absent file means the
 * identity mapping — imported content already carries normalized keys.
 * A malformed file fails closed by throwing at startup.
 */
export function loadQuestStorageAliases(
  contentDir = join(CONTENT_DIR, "quests"),
): QuestStorageAliases {
  let raw: string;
  try {
    raw = readFileSync(join(contentDir, "storage-aliases.json"), "utf8");
  } catch {
    return { canonicalOf: (key) => key, size: 0 };
  }
  const parsed: unknown = JSON.parse(raw);
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error("quest storage aliases must be an object");
  }
  const record = parsed as Record<string, unknown>;
  if (record.formatVersion !== 1) {
    throw new Error("quest storage aliases have an unsupported formatVersion");
  }
  const aliases = record.aliases;
  if (
    typeof aliases !== "object" ||
    aliases === null ||
    Array.isArray(aliases)
  ) {
    throw new Error("quest storage aliases are malformed");
  }
  const map = new Map<string, string>();
  for (const [alias, canonical] of Object.entries(
    aliases as Record<string, unknown>,
  )) {
    if (
      typeof canonical !== "string" ||
      !STORAGE_KEY.test(alias) ||
      !STORAGE_KEY.test(canonical) ||
      alias.length > 192 ||
      canonical.length > 192
    ) {
      throw new Error(`quest storage alias ${alias} is malformed`);
    }
    map.set(alias, canonical);
  }
  return {
    canonicalOf: (key) => map.get(key) ?? key,
    size: map.size,
  };
}
