import type { SpellDefinition } from "../../Spell";

export const exanaPox: SpellDefinition = {
  id: "exana-pox",
  numericId: 29,
  sourcePath: "data/scripts/spells/healing/cure_poison.lua",
  name: "Cure Poison",
  words: "exana pox",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: [
    "Druid",
    "Elder Druid",
    "Knight",
    "Elite Knight",
    "Paladin",
    "Royal Paladin",
    "Sorcerer",
    "Master Sorcerer",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 10,
  requiredMagicLevel: 0,
  manaCost: 30,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 6000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "poison",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
