import type { SpellDefinition } from "../../Spell";

export const exanaMort: SpellDefinition = {
  id: "exana-mort",
  numericId: 147,
  sourcePath: "data/scripts/spells/healing/cure_curse.lua",
  name: "Cure Curse",
  words: "exana mort",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 80,
  requiredMagicLevel: 0,
  manaCost: 40,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 6000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "curse",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
