import type { SpellDefinition } from "../../Spell";

export const exanaFlam: SpellDefinition = {
  id: "exana-flam",
  numericId: 145,
  sourcePath: "data/scripts/spells/healing/cure_burning.lua",
  name: "Cure Burning",
  words: "exana flam",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 30,
  requiredMagicLevel: 0,
  manaCost: 30,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 6000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "fire",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
