import type { SpellDefinition } from "../../Spell";

export const exuraGran: SpellDefinition = {
  id: "exura-gran",
  numericId: 2,
  sourcePath: "data/scripts/spells/healing/intense_healing.lua",
  name: "Intense Healing",
  words: "exura gran",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: [
    "Druid",
    "Elder Druid",
    "Paladin",
    "Royal Paladin",
    "Sorcerer",
    "Master Sorcerer",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 20,
  requiredMagicLevel: 0,
  manaCost: 70,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 3.184 + 20,
    maximum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 5.59 + 35,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
