import type { SpellDefinition } from "../../Spell";

export const exuraGranSan: SpellDefinition = {
  id: "exura-gran-san",
  numericId: 36,
  sourcePath: "data/scripts/spells/healing/salvation.lua",
  name: "Salvation",
  words: "exura gran san",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 60,
  requiredMagicLevel: 0,
  manaCost: 210,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 12 + 75,
    maximum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 20 + 125,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
