import type { SpellDefinition } from "../../Spell";

export const exuraDis: SpellDefinition = {
  id: "exura-dis",
  numericId: 166,
  sourcePath: "data/scripts/spells/healing/practise_healing.lua",
  name: "Practise Healing",
  words: "exura dis",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: [
    "Knight",
    "Paladin",
    "Sorcerer",
    "Druid",
    "Elite Knight",
    "Royal Paladin",
    "Master Sorcerer",
    "Elder Druid",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 1,
  requiredMagicLevel: 0,
  manaCost: 5,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: () => 5,
    maximum: () => 9,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
