import type { SpellDefinition } from "../../Spell";

export const exuraIco: SpellDefinition = {
  id: "exura-ico",
  numericId: 123,
  sourcePath: "data/scripts/spells/healing/wound_cleansing.lua",
  name: "Wound Cleansing",
  words: "exura ico",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 8,
  requiredMagicLevel: 0,
  manaCost: 40,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 4 + 25,
    maximum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 7.95 + 51,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
