import type { SpellDefinition } from "../../Spell";

export const exura: SpellDefinition = {
  id: "exura",
  numericId: 1,
  sourcePath: "data/scripts/spells/healing/light_healing.lua",
  name: "Light Healing",
  words: "exura",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: [
    "Druid",
    "Elder Druid",
    "Paladin",
    "Royal Paladin",
    "Sorcerer",
    "Master Sorcerer",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 8,
  requiredMagicLevel: 0,
  manaCost: 20,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 1.4 + 8,
    maximum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 1.795 + 11,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
