import type { SpellDefinition } from "../../Spell";

export const exuraGranTio: SpellDefinition = {
  id: "exura-gran-tio",
  numericId: 273,
  sourcePath: "data/scripts/spells/healing/spirit_mend.lua",
  name: "Spirit Mend",
  words: "exura gran tio",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Monk", "Exalted Monk"],
  requiredLevel: 80,
  requiredMagicLevel: 0,
  manaCost: 210,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 7.22 + 44,
    maximum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 12.79 + 79,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
