import type { SpellDefinition } from "../../Spell";

export const exuraGranIco: SpellDefinition = {
  id: "exura-gran-ico",
  numericId: 158,
  sourcePath: "data/scripts/spells/healing/intense_wound_cleansing.lua",
  name: "Intense Wound Cleansing",
  words: "exura gran ico",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 80,
  requiredMagicLevel: 0,
  manaCost: 200,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 600_000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 70 + 438,
    maximum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 92 + 544,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
