import type { SpellDefinition } from "../../Spell";

export const exuraInfirIco: SpellDefinition = {
  id: "exura-infir-ico",
  numericId: 170,
  sourcePath: "data/scripts/spells/healing/bruise_bane.lua",
  name: "Bruise Bane",
  words: "exura infir ico",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 1,
  requiredMagicLevel: 0,
  manaCost: 10,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 1.795,
    maximum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 1.795 + 5,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
