import type { SpellDefinition } from "../../Spell";

export const exuraSan: SpellDefinition = {
  id: "exura-san",
  numericId: 125,
  sourcePath: "data/scripts/spells/healing/divine_healing.lua",
  name: "Divine Healing",
  words: "exura san",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 35,
  requiredMagicLevel: 0,
  manaCost: 160,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 7.22 + 44,
    maximum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 12.79 + 79,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
