import type { SpellDefinition } from "../../Spell";

export const exuraMedIco: SpellDefinition = {
  id: "exura-med-ico",
  numericId: 239,
  sourcePath: "data/scripts/spells/healing/fair_wound_cleansing.lua",
  name: "Fair Wound Cleansing",
  words: "exura med ico",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 300,
  requiredMagicLevel: 0,
  manaCost: 90,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => (level * 0.2 + magicLevel * 4 + 25) * 2,
    maximum: ({ level, magicLevel }) => (level * 0.2 + magicLevel * 7.95 + 51) * 2,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
