import type { SpellDefinition } from "../../Spell";

export const exuraGranSio: SpellDefinition = {
  id: "exura-gran-sio",
  numericId: 242,
  sourcePath: "data/scripts/spells/healing/nature's_embrace.lua",
  name: "Nature's Embrace",
  words: "exura gran sio",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 300,
  requiredMagicLevel: 0,
  manaCost: 400,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 60_000,
  groupCooldownMs: [1000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 2.5 + magicLevel * 20,
    maximum: ({ level, magicLevel }) => level / 2.5 + magicLevel * 28,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: {
    targetPlayerOnly: true,
    targetPartyMemberOnly: true,
    allowSelf: false,
    excludedVocations: [],
    casterEffectId: 15,
  },
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
