import type { SpellDefinition } from "../../Spell";

export const exuraTioSio: SpellDefinition = {
  id: "exura-tio-sio",
  numericId: 297,
  sourcePath: "data/scripts/spells/healing/restore_balance.lua",
  name: "Restore Balance",
  words: "exura tio sio",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Monk", "Exalted Monk"],
  requiredLevel: 18,
  requiredMagicLevel: 0,
  manaCost: 120,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 2000,
  groupCooldownMs: [1000],
  range: 7,
  lineOfSight: false,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level * 0.5 + magicLevel * 10 + 3,
    maximum: ({ level, magicLevel }) => level * 0.5 + magicLevel * 14 + 5,
  },
  effectId: 15,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
