import type { SpellDefinition } from "../../Spell";

export const exuraSio: SpellDefinition = {
  id: "exura-sio",
  numericId: 84,
  sourcePath: "data/scripts/spells/healing/heal_friend.lua",
  name: "Heal Friend",
  words: "exura sio",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 18,
  requiredMagicLevel: 0,
  manaCost: 120,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 7,
  lineOfSight: false,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 10 + 3,
    maximum: ({ level, magicLevel }) => level * 0.2 + magicLevel * 14 + 5,
  },
  effectId: 15,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: {
    targetPlayerOnly: true,
    allowSelf: false,
    excludedVocations: [],
    casterEffectId: 15,
  },
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
