import type { SpellDefinition } from "../../Spell";

export const exuraVita: SpellDefinition = {
  id: "exura-vita",
  numericId: 3,
  sourcePath: "data/scripts/spells/healing/ultimate_healing.lua",
  name: "Ultimate Healing",
  words: "exura vita",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid", "Sorcerer", "Master Sorcerer"],
  requiredLevel: 30,
  requiredMagicLevel: 0,
  manaCost: 160,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 6.8 + 42,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 12.9 + 90,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
