import type { SpellDefinition } from "../../Spell";

export const exuraMaxVita: SpellDefinition = {
  id: "exura-max-vita",
  numericId: 241,
  sourcePath: "data/scripts/spells/healing/restoration.lua",
  name: "Restoration",
  words: "exura max vita",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Sorcerer", "Elder Druid", "Master Sorcerer"],
  requiredLevel: 300,
  requiredMagicLevel: 0,
  manaCost: 260,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 6000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level * 1.4 / 5 + magicLevel * 9.22 * 1.4 + 44 * 1.4,
    maximum: ({ level, magicLevel }) => level * 1.4 / 5 + magicLevel * 10.79 * 1.4 + 79 * 1.4,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
