import type { SpellDefinition } from "../../Spell";

export const exuraInfir: SpellDefinition = {
  id: "exura-infir",
  numericId: 174,
  sourcePath: "data/scripts/spells/healing/magic_patch.lua",
  name: "Magic Patch",
  words: "exura infir",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: [
    "Druid",
    "Elder Druid",
    "Paladin",
    "Royal Paladin",
    "Sorcerer",
    "Master Sorcerer",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 1,
  requiredMagicLevel: 0,
  manaCost: 6,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level * 0 + magicLevel * 0.1614 + 8,
    maximum: ({ level, magicLevel }) => level * 0 + magicLevel * 0.2468 + 15,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
