import type { SpellDefinition } from "../../Spell";

export const uturaGran: SpellDefinition = {
  id: "utura-gran",
  numericId: 160,
  sourcePath: "data/scripts/spells/healing/intense_recovery.lua",
  name: "Intense Recovery",
  words: "utura gran",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight", "Paladin", "Royal Paladin"],
  requiredLevel: 100,
  requiredMagicLevel: 0,
  manaCost: 165,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 0,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 15,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "regeneration",
    durationMs: 60_000,
    magnitude: 40,
    tickIntervalMs: 3000,
    damageType: "healing",
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
