import type { SpellDefinition } from "../../Spell";

export const utura: SpellDefinition = {
  id: "utura",
  numericId: 159,
  sourcePath: "data/scripts/spells/healing/recovery.lua",
  name: "Recovery",
  words: "utura",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight", "Paladin", "Royal Paladin"],
  requiredLevel: 50,
  requiredMagicLevel: 0,
  manaCost: 75,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 60_000,
  groupCooldownMs: [1000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 15,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "regeneration",
    durationMs: 60_000,
    magnitude: 20,
    tickIntervalMs: 3000,
    damageType: "healing",
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
