// Generated by tools/importWheelGemMods.mjs from otclient-mehah's
// modules/game_wheel/classes/icons.lua — do not edit by hand.
// Mod ids match Canary's WheelGemBasicModifier_t / WheelGemSupremeModifier_t
// enum values and index the icon sprite sheets (basic: x = id * 30 in
// icons-skillwheel-basicmods.png, supreme: x = id * 35 in
// icons-skillwheel-suprememods.png).
import type {
  GemBasicModDefinition,
  GemSupremeModDefinition,
} from "./gemAtelier";

export const GEM_BASIC_MODS: ReadonlyArray<GemBasicModDefinition> = [
  {
    id: 0,
    tooltip: "+%s%% Physical Resistance",
    effects: [
      {
        kind: "resistance",
        element: "physical",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 1,
    tooltip: "+%s%% Holy Resistance",
    effects: [
      {
        kind: "resistance",
        element: "holy",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 2,
    tooltip: "+%s%% Death Resistance",
    effects: [
      {
        kind: "resistance",
        element: "death",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 3,
    tooltip: "+%s%% Fire Resistance",
    effects: [
      {
        kind: "resistance",
        element: "fire",
        percent: 2,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 4,
    tooltip: "+%s%% Earth Resistance",
    effects: [
      {
        kind: "resistance",
        element: "earth",
        percent: 2,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 5,
    tooltip: "+%s%% Ice Resistance",
    effects: [
      {
        kind: "resistance",
        element: "ice",
        percent: 2,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 6,
    tooltip: "+%s%% Energy Resistance",
    effects: [
      {
        kind: "resistance",
        element: "energy",
        percent: 2,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 7,
    tooltip: "+%s%% Holy Resistance\n-1%% Death Resistance",
    effects: [
      {
        kind: "resistance",
        element: "holy",
        percent: 1.5,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "death",
        percent: -1,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 8,
    tooltip: "+%s%% Death Resistance\n-1%% Holy Resistance",
    effects: [
      {
        kind: "resistance",
        element: "death",
        percent: 1.5,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "holy",
        percent: -1,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 9,
    tooltip: "+%s%% Fire Resistance\n+%s%% Earth Resistance",
    effects: [
      {
        kind: "resistance",
        element: "fire",
        percent: 1,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "earth",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 10,
    tooltip: "+%s%% Fire Resistance\n+%s%% Ice Resistance",
    effects: [
      {
        kind: "resistance",
        element: "fire",
        percent: 1,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "ice",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 11,
    tooltip: "+%s%% Fire Resistance\n+%s%% Energy Resistance",
    effects: [
      {
        kind: "resistance",
        element: "fire",
        percent: 1,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "energy",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 12,
    tooltip: "+%s%% Earth Resistance\n+%s%% Ice Resistance",
    effects: [
      {
        kind: "resistance",
        element: "earth",
        percent: 1,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "ice",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 13,
    tooltip: "+%s%% Earth Resistance\n+%s%% Energy Resistance",
    effects: [
      {
        kind: "resistance",
        element: "earth",
        percent: 1,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "energy",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 14,
    tooltip: "+%s%% Ice Resistance\n+%s%% Energy Resistance",
    effects: [
      {
        kind: "resistance",
        element: "ice",
        percent: 1,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "energy",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 15,
    tooltip: "+%s%% Fire Resistance\n-2%% Earth Resistance",
    effects: [
      {
        kind: "resistance",
        element: "fire",
        percent: 3,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "earth",
        percent: -2,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 16,
    tooltip: "+%s%% Fire Resistance\n-2%% Ice Resistance",
    effects: [
      {
        kind: "resistance",
        element: "fire",
        percent: 3,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "ice",
        percent: -2,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 17,
    tooltip: "+%s%% Fire Resistance\n-2%% Energy Resistance",
    effects: [
      {
        kind: "resistance",
        element: "fire",
        percent: 3,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "energy",
        percent: -2,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 18,
    tooltip: "+%s%% Earth Resistance\n-2%% Fire Resistance",
    effects: [
      {
        kind: "resistance",
        element: "earth",
        percent: 3,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "fire",
        percent: -2,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 19,
    tooltip: "+%s%% Earth Resistance\n-2%% Ice Resistance",
    effects: [
      {
        kind: "resistance",
        element: "earth",
        percent: 3,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "ice",
        percent: -2,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 20,
    tooltip: "+%s%% Earth Resistance\n-2%% Energy Resistance",
    effects: [
      {
        kind: "resistance",
        element: "earth",
        percent: 3,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "energy",
        percent: -2,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 21,
    tooltip: "+%s%% Ice Resistance\n-2%% Earth Resistance",
    effects: [
      {
        kind: "resistance",
        element: "ice",
        percent: 3,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "earth",
        percent: -2,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 22,
    tooltip: "+%s%% Ice Resistance\n-2%% Fire Resistance",
    effects: [
      {
        kind: "resistance",
        element: "ice",
        percent: 3,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "fire",
        percent: -2,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 23,
    tooltip: "+%s%% Ice Resistance\n-2%% Energy Resistance",
    effects: [
      {
        kind: "resistance",
        element: "ice",
        percent: 3,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "energy",
        percent: -2,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 24,
    tooltip: "+%s%% Energy Resistance\n-2%% Earth Resistance",
    effects: [
      {
        kind: "resistance",
        element: "energy",
        percent: 3,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "earth",
        percent: -2,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 25,
    tooltip: "+%s%% Energy Resistance\n-2%% Ice Resistance",
    effects: [
      {
        kind: "resistance",
        element: "energy",
        percent: 3,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "ice",
        percent: -2,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 26,
    tooltip: "+%s%% Energy Resistance\n-2%% Fire Resistance",
    effects: [
      {
        kind: "resistance",
        element: "energy",
        percent: 3,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "fire",
        percent: -2,
        scalesWithGrade: false
      }
    ]
  },
  {
    id: 27,
    tooltip: "+%s%% Mana Drain Resistance",
    effects: [
      {
        kind: "resistance",
        element: "mana-drain",
        percent: 3,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 28,
    tooltip: "+%s%% Life Drain Resistance",
    effects: [
      {
        kind: "resistance",
        element: "life-drain",
        percent: 3,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 29,
    tooltip: "+%s%% Mana Drain Resistance\n+%s%% Life Drain Resistance",
    effects: [
      {
        kind: "resistance",
        element: "mana-drain",
        percent: 1.5,
        scalesWithGrade: true
      },
      {
        kind: "resistance",
        element: "life-drain",
        percent: 1.5,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 30,
    tooltip: "+%s%% Mitigation Multiplier",
    effects: [
      {
        kind: "mitigation",
        percent: 5
      }
    ]
  },
  {
    id: 31,
    tooltip: "+%s Hit Points",
    effects: [
      {
        kind: "stat",
        stat: "health",
        step: 100
      }
    ]
  },
  {
    id: 33,
    tooltip: "+%s Mana\n+%s%% Fire Resistance",
    effects: [
      {
        kind: "stat",
        stat: "mana",
        step: 50
      },
      {
        kind: "resistance",
        element: "fire",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 34,
    tooltip: "+%s Mana\n+%s%% Energy Resistance",
    effects: [
      {
        kind: "stat",
        stat: "mana",
        step: 50
      },
      {
        kind: "resistance",
        element: "energy",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 35,
    tooltip: "+%s Mana\n+%s%% Earth Resistance",
    effects: [
      {
        kind: "stat",
        stat: "mana",
        step: 50
      },
      {
        kind: "resistance",
        element: "earth",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 36,
    tooltip: "+%s Mana\n+%s%% Ice Resistance",
    effects: [
      {
        kind: "stat",
        stat: "mana",
        step: 50
      },
      {
        kind: "resistance",
        element: "ice",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 37,
    tooltip: "+%s Mana",
    effects: [
      {
        kind: "stat",
        stat: "mana",
        step: 100
      }
    ]
  },
  {
    id: 38,
    tooltip: "+%s Health\n+%s%% Fire Resistance",
    effects: [
      {
        kind: "stat",
        stat: "health",
        step: 50
      },
      {
        kind: "resistance",
        element: "fire",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 39,
    tooltip: "+%s Health\n+%s%% Energy Resistance",
    effects: [
      {
        kind: "stat",
        stat: "health",
        step: 50
      },
      {
        kind: "resistance",
        element: "energy",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 40,
    tooltip: "+%s Health\n+%s%% Earth Resistance",
    effects: [
      {
        kind: "stat",
        stat: "health",
        step: 50
      },
      {
        kind: "resistance",
        element: "earth",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 41,
    tooltip: "+%s Health\n+%s%% Ice Resistance",
    effects: [
      {
        kind: "stat",
        stat: "health",
        step: 50
      },
      {
        kind: "resistance",
        element: "ice",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 44,
    tooltip: "+%s Capacity\n+%s%% Fire Resistance",
    effects: [
      {
        kind: "stat",
        stat: "capacity",
        step: 50
      },
      {
        kind: "resistance",
        element: "fire",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 45,
    tooltip: "+%s Capacity\n+%s%% Energy Resistance",
    effects: [
      {
        kind: "stat",
        stat: "capacity",
        step: 50
      },
      {
        kind: "resistance",
        element: "energy",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 46,
    tooltip: "+%s Capacity\n+%s%% Earth Resistance",
    effects: [
      {
        kind: "stat",
        stat: "capacity",
        step: 50
      },
      {
        kind: "resistance",
        element: "earth",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 47,
    tooltip: "+%s Capacity\n+%s%% Ice Resistance",
    effects: [
      {
        kind: "stat",
        stat: "capacity",
        step: 50
      },
      {
        kind: "resistance",
        element: "ice",
        percent: 1,
        scalesWithGrade: true
      }
    ]
  },
  {
    id: 48,
    tooltip: "+%s Capacity",
    effects: [
      {
        kind: "stat",
        stat: "capacity",
        step: 100
      }
    ]
  }
];

export const GEM_SUPREME_MODS: ReadonlyArray<GemSupremeModDefinition> = [
  {
    id: 0,
    name: "Dodge",
    tooltip: "+%s%% Dodge",
    vocations: "all",
    effect: {
      kind: "dodge",
      percent: 0.28
    }
  },
  {
    id: 1,
    name: "Critical Extra Damage",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: "all",
    effect: {
      kind: "critical-damage",
      percent: 2
    }
  },
  {
    id: 2,
    name: "Life Leech",
    tooltip: "+%s%% Life Leech",
    vocations: "all",
    effect: {
      kind: "life-leech",
      percent: 2
    }
  },
  {
    id: 3,
    name: "Mana Leech",
    tooltip: "+%s%% Mana Leech",
    vocations: "all",
    effect: {
      kind: "mana-leech",
      percent: 0.8
    }
  },
  {
    id: 4,
    name: "Aug. Ultimate Healing",
    tooltip: "+%s%% Base Healing",
    vocations: [
      "Sorcerer",
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseI: 5,
      momentum: false
    }
  },
  {
    id: 5,
    name: "Revelation Mastery",
    tooltip: "+%s Gift of Life",
    vocations: "all",
    effect: {
      kind: "revelation",
      domain: "green",
      points: 150
    }
  },
  {
    id: 6,
    name: "Aug. Avatar of Steel",
    tooltip: "-900s Cooldown\n+%s%% Momentum",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseII: 0.33,
      momentum: true
    }
  },
  {
    id: 7,
    name: "Aug. Executioner's Throw",
    tooltip: "-2s Cooldown\n+%s%% Momentum",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseII: 0.33,
      momentum: true
    }
  },
  {
    id: 8,
    name: "Aug. Executioner's Throw",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseI: 6,
      momentum: false
    }
  },
  {
    id: 9,
    name: "Aug. Executioner's Throw",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 10,
    name: "Aug. Fierce Berserk",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseI: 5,
      momentum: false
    }
  },
  {
    id: 11,
    name: "Aug. Fierce Berserk",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 12,
    name: "Aug. Berserk",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseI: 5,
      momentum: false
    }
  },
  {
    id: 13,
    name: "Aug. Berserk",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 14,
    name: "Aug. Front Sweep",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 15,
    name: "Aug. Front Sweep",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 16,
    name: "Aug. Groundshaker",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseI: 6.5,
      momentum: false
    }
  },
  {
    id: 17,
    name: "Aug. Groundshaker",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 18,
    name: "Aug. Annihilation",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 19,
    name: "Aug. Annihilation",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseI: 15,
      momentum: false
    }
  },
  {
    id: 20,
    name: "Aug. Fair Wound Cleansing",
    tooltip: "+%s%% Base Healing",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "spell",
      baseI: 10,
      momentum: false
    }
  },
  {
    id: 21,
    name: "Revelation Mastery",
    tooltip: "+%s Avatar of Steel",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "revelation",
      domain: "purple",
      points: 150
    }
  },
  {
    id: 22,
    name: "Revelation Mastery",
    tooltip: "+%s Executioner's Throw",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "revelation",
      domain: "red",
      points: 150
    }
  },
  {
    id: 23,
    name: "Revelation Mastery",
    tooltip: "+%s Combat Mastery",
    vocations: [
      "Knight"
    ],
    effect: {
      kind: "revelation",
      domain: "blue",
      points: 150
    }
  },
  {
    id: 24,
    name: "Aug. Avatar of Light",
    tooltip: "-900s Cooldown\n+%s%% Momentum",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseII: 0.33,
      momentum: true
    }
  },
  {
    id: 25,
    name: "Aug. Divine Dazzle",
    tooltip: "-4s Cooldown\n+%s%% Momentum",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseII: 0.33,
      momentum: true
    }
  },
  {
    id: 26,
    name: "Aug. Divine Grenade",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseI: 6,
      momentum: false
    }
  },
  {
    id: 27,
    name: "Aug. Divine Grenade",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 28,
    name: "Aug. Divine Caldera",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseI: 5,
      momentum: false
    }
  },
  {
    id: 29,
    name: "Aug. Divine Caldera",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 30,
    name: "Aug. Divine Missile",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 31,
    name: "Aug. Divine Missile",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 32,
    name: "Aug. Ethereal Spear",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseI: 10,
      momentum: false
    }
  },
  {
    id: 33,
    name: "Aug. Ethereal Spear",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseI: 15,
      momentum: false
    }
  },
  {
    id: 34,
    name: "Aug. Strong Ethereal Spear",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 35,
    name: "Aug. Strong Ethereal Spear",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 36,
    name: "Aug. Divine Empowerment",
    tooltip: "-6s Cooldown\n+%s%% Momentum",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseII: 0.33,
      momentum: true
    }
  },
  {
    id: 37,
    name: "Aug. Divine Grenade",
    tooltip: "-2s Cooldown\n+%s%% Momentum",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseII: 0.33,
      momentum: true
    }
  },
  {
    id: 38,
    name: "Aug. Salvation",
    tooltip: "+%s%% Base Healing",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "spell",
      baseI: 6,
      momentum: false
    }
  },
  {
    id: 39,
    name: "Revelation Mastery",
    tooltip: "+%s Avatar of Light",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "revelation",
      domain: "purple",
      points: 150
    }
  },
  {
    id: 40,
    name: "Revelation Mastery",
    tooltip: "+%s Divine Grenade",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "revelation",
      domain: "red",
      points: 150
    }
  },
  {
    id: 41,
    name: "Revelation Mastery",
    tooltip: "+%s Divine Empowerment",
    vocations: [
      "Paladin"
    ],
    effect: {
      kind: "revelation",
      domain: "blue",
      points: 150
    }
  },
  {
    id: 42,
    name: "Aug. Avatar of Storm",
    tooltip: "-900s Cooldown\n+%s%% Momentum",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseII: 0.33,
      momentum: true
    }
  },
  {
    id: 43,
    name: "Aug. Energy Wave",
    tooltip: "-1s Cooldown\n+%s%% Momentum",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseII: 0.33,
      momentum: true
    }
  },
  {
    id: 44,
    name: "Aug. Great Death Beam",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseI: 10,
      momentum: false
    }
  },
  {
    id: 45,
    name: "Aug. Great Death Beam",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseI: 15,
      momentum: false
    }
  },
  {
    id: 46,
    name: "Aug. Hell's Core",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 47,
    name: "Aug. Hell's Core",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 48,
    name: "Aug. Energy Wave",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseI: 5,
      momentum: false
    }
  },
  {
    id: 49,
    name: "Aug. Energy Wave",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 50,
    name: "Aug. Great Fire Wave",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseI: 5,
      momentum: false
    }
  },
  {
    id: 51,
    name: "Aug. Great Fire Wave",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 52,
    name: "Aug. Rage of the Skies",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 53,
    name: "Aug. Rage of the Skies",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 54,
    name: "Aug. Great Energy Beam",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseI: 10,
      momentum: false
    }
  },
  {
    id: 55,
    name: "Aug. Great Energy Beam",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "spell",
      baseI: 15,
      momentum: false
    }
  },
  {
    id: 56,
    name: "Revelation Mastery",
    tooltip: "+%s Avatar of Storm",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "revelation",
      domain: "purple",
      points: 150
    }
  },
  {
    id: 57,
    name: "Revelation Mastery",
    tooltip: "+%s Beam Mastery",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "revelation",
      domain: "red",
      points: 150
    }
  },
  {
    id: 58,
    name: "Revelation Mastery",
    tooltip: "+%s Drain Body",
    vocations: [
      "Sorcerer"
    ],
    effect: {
      kind: "revelation",
      domain: "blue",
      points: 150
    }
  },
  {
    id: 59,
    name: "Aug. Avatar of Nature",
    tooltip: "-900s Cooldown\n+%s%% Momentum",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseII: 0.33,
      momentum: true
    }
  },
  {
    id: 60,
    name: "Aug. Nature's Embrace",
    tooltip: "-10s Cooldown\n+%s%% Momentum",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseII: 0.33,
      momentum: true
    }
  },
  {
    id: 61,
    name: "Aug. Terra Burst",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseI: 7,
      momentum: false
    }
  },
  {
    id: 62,
    name: "Aug. Terra Burst",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 63,
    name: "Aug. Ice Burst",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseI: 7,
      momentum: false
    }
  },
  {
    id: 64,
    name: "Aug. Ice Burst",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 65,
    name: "Aug. Eternal Winter",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 66,
    name: "Aug. Eternal Winter",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 67,
    name: "Aug. Terra Wave",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseI: 5,
      momentum: false
    }
  },
  {
    id: 68,
    name: "Aug. Terra Wave",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseI: 12,
      momentum: false
    }
  },
  {
    id: 69,
    name: "Aug. Strong Ice Wave",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 70,
    name: "Aug. Strong Ice Wave",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseI: 15,
      momentum: false
    }
  },
  {
    id: 71,
    name: "Aug. Heal Friend",
    tooltip: "+%s%% Base Healing",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseI: 5,
      momentum: false
    }
  },
  {
    id: 72,
    name: "Aug. Mass Healing",
    tooltip: "+%s%% Base Healing",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "spell",
      baseI: 5,
      momentum: false
    }
  },
  {
    id: 73,
    name: "Revelation Mastery",
    tooltip: "+%s Avatar of Nature",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "revelation",
      domain: "purple",
      points: 150
    }
  },
  {
    id: 74,
    name: "Revelation Mastery",
    tooltip: "+%s Blessing of the Grove",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "revelation",
      domain: "red",
      points: 150
    }
  },
  {
    id: 75,
    name: "Revelation Mastery",
    tooltip: "+%s Twin Bursts",
    vocations: [
      "Druid"
    ],
    effect: {
      kind: "revelation",
      domain: "blue",
      points: 150
    }
  },
  {
    id: 76,
    name: "Aug. Avatar of Balance",
    tooltip: "-900s Cooldown\n+%s%% Momentum",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseII: 0.33,
      momentum: true
    }
  },
  {
    id: 77,
    name: "Aug. Spirit Mend",
    tooltip: "+%s%% Base Healing",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseI: 6,
      momentum: false
    }
  },
  {
    id: 78,
    name: "Aug. Spiritual Outburst",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseI: 5,
      momentum: false
    }
  },
  {
    id: 79,
    name: "Aug. Spiritual Outburst",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 80,
    name: "Aug. Forceful Uppercut",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseI: 10,
      momentum: false
    }
  },
  {
    id: 81,
    name: "Aug. Forceful Uppercut",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 82,
    name: "Aug. Flurry of Blows",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseI: 6.5,
      momentum: false
    }
  },
  {
    id: 83,
    name: "Aug. Flurry of Blows",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 84,
    name: "Aug. Greater Flurry of Blows",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseI: 5,
      momentum: false
    }
  },
  {
    id: 85,
    name: "Aug. Greater Flurry of Blows",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 86,
    name: "Aug. Sweeping Takedown",
    tooltip: "+%s%% Base Damage",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseI: 5,
      momentum: false
    }
  },
  {
    id: 87,
    name: "Aug. Sweeping Takedown",
    tooltip: "+%s%% Critical Extra Damage",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseI: 8,
      momentum: false
    }
  },
  {
    id: 88,
    name: "Aug. Focus Serenity",
    tooltip: "-150s Cooldown\n+%s%% Momentum",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseII: 0.33,
      momentum: true
    }
  },
  {
    id: 89,
    name: "Aug. Focus Harmony",
    tooltip: "-30s Cooldown\n+%s%% Momentum",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseII: 0.33,
      momentum: true
    }
  },
  {
    id: 90,
    name: "Aug. Mass Spirit Mend",
    tooltip: "+%s%% Base Healing",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "spell",
      baseI: 5,
      momentum: false
    }
  },
  {
    id: 91,
    name: "Revelation Mastery",
    tooltip: "+%s Avatar of Balance",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "revelation",
      domain: "purple",
      points: 150
    }
  },
  {
    id: 92,
    name: "Revelation Mastery",
    tooltip: "+%s Spiritual Outburst",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "revelation",
      domain: "red",
      points: 150
    }
  },
  {
    id: 93,
    name: "Revelation Mastery",
    tooltip: "+%s Ascetic",
    vocations: [
      "Monk"
    ],
    effect: {
      kind: "revelation",
      domain: "blue",
      points: 150
    }
  }
];
