import type { SpellDefinition } from "../../Spell";

export const antidoteRune: SpellDefinition = {
  id: "antidote-rune",
  numericId: null,
  sourcePath: "data/scripts/runes/antidote_rune.lua",
  name: "antidote rune",
  words: null,
  origin: "rune",
  runeItemTypeId: 3153,
  charges: 1,
  vocations: [
    "Knight",
    "Paladin",
    "Sorcerer",
    "Druid",
    "Elite Knight",
    "Royal Paladin",
    "Master Sorcerer",
    "Elder Druid",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 15,
  requiredMagicLevel: 0,
  manaCost: 0,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "poison",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
