import type { SpellDefinition } from "../../Spell";

export const explosionRune: SpellDefinition = {
  id: "explosion-rune",
  numericId: 18,
  sourcePath: "data/scripts/runes/explosion.lua",
  name: "explosion rune",
  words: null,
  origin: "rune",
  runeItemTypeId: 3200,
  charges: 6,
  vocations: [
    "Knight",
    "Paladin",
    "Sorcerer",
    "Druid",
    "Elite Knight",
    "Royal Paladin",
    "Master Sorcerer",
    "Elder Druid",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 31,
  requiredMagicLevel: 6,
  manaCost: 0,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 7,
  lineOfSight: true,
  targetKind: "position",
  aggressive: false,
  needWeapon: false,
  damageType: "physical",
  formula: {
    kind: "level-magic",
    minimum: () => 0,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 4.8,
  },
  effectId: 5,
  missileId: 41,
  blockArmor: true,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [
      { x: 0, y: -1 },
      { x: -1, y: 0 },
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 0, y: 1 },
    ],
    directional: false,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
