import type { SpellDefinition } from "../../Spell";

export const holyMissileRune: SpellDefinition = {
  id: "holy-missile-rune",
  numericId: 130,
  sourcePath: "data/scripts/runes/holy_missile.lua",
  name: "holy missile rune",
  words: null,
  origin: "rune",
  runeItemTypeId: 3182,
  charges: 5,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 27,
  requiredMagicLevel: 4,
  manaCost: 0,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "holy",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 1.79 + 11,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 3.75 + 24,
  },
  effectId: 40,
  missileId: 31,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
