import type { SpellDefinition } from "../../Spell";

export const icicleRune: SpellDefinition = {
  id: "icicle-rune",
  numericId: 114,
  sourcePath: "data/scripts/runes/icicle.lua",
  name: "icicle rune",
  words: null,
  origin: "rune",
  runeItemTypeId: 3158,
  charges: 5,
  vocations: [
    "Knight",
    "Paladin",
    "Sorcerer",
    "Druid",
    "Elite Knight",
    "Royal Paladin",
    "Master Sorcerer",
    "Elder Druid",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 28,
  requiredMagicLevel: 4,
  manaCost: 0,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "ice",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 1.81 + 10,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 3 + 18,
  },
  effectId: 42,
  missileId: 29,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
