import type { SpellDefinition } from "../../Spell";

export const intenseHealingRune: SpellDefinition = {
  id: "intense-healing-rune",
  numericId: 4,
  sourcePath: "data/scripts/runes/intense_healing_rune.lua",
  name: "intense healing rune",
  words: null,
  origin: "rune",
  runeItemTypeId: 3152,
  charges: 1,
  vocations: [
    "Knight",
    "Paladin",
    "Sorcerer",
    "Druid",
    "Elite Knight",
    "Royal Paladin",
    "Master Sorcerer",
    "Elder Druid",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 15,
  requiredMagicLevel: 1,
  manaCost: 0,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 3.2 + 20,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 5.4 + 40,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: {
    targetPlayerOnly: true,
    allowSelf: true,
    excludedVocations: [],
    casterEffectId: 0,
  },
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
