import type { SpellDefinition } from "../../Spell";

export const lightMagicMissileRune: SpellDefinition = {
  id: "light-magic-missile-rune",
  numericId: 7,
  sourcePath: "data/scripts/runes/light_magic_missile.lua",
  name: "light magic missile rune",
  words: null,
  origin: "rune",
  runeItemTypeId: 3174,
  charges: 10,
  vocations: [
    "Knight",
    "Paladin",
    "Sorcerer",
    "Druid",
    "Elite Knight",
    "Royal Paladin",
    "Master Sorcerer",
    "Elder Druid",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 15,
  requiredMagicLevel: 0,
  manaCost: 0,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "energy",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 0.4 + 2,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 0.81 + 4,
  },
  effectId: 38,
  missileId: 5,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
