import type { SpellDefinition } from "../../Spell";

export const lightestMissileRune: SpellDefinition = {
  id: "lightest-missile-rune",
  numericId: 7,
  sourcePath: "data/scripts/runes/lightest_missile.lua",
  name: "lightest missile rune",
  words: null,
  origin: "rune",
  runeItemTypeId: 21_352,
  charges: 10,
  vocations: [
    "Sorcerer",
    "Master Sorcerer",
    "Druid",
    "Elder Druid",
    "Paladin",
    "Royal Paladin",
  ],
  requiredLevel: 1,
  requiredMagicLevel: 0,
  manaCost: 0,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "energy",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 0.4 + 3,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 0.8 + 5,
  },
  effectId: 38,
  missileId: 5,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
