import type { SpellDefinition } from "../../Spell";

export const lightestMagicMissileRune: SpellDefinition = {
  id: "lightest-magic-missile-rune",
  numericId: 7,
  sourcePath: "data/scripts/runes/lightest_magic_missile.lua",
  name: "lightest magic missile rune",
  words: null,
  origin: "rune",
  runeItemTypeId: 17_512,
  charges: 10,
  vocations: [
    "Sorcerer",
    "Master Sorcerer",
    "Druid",
    "Elder Druid",
    "Paladin",
    "Royal Paladin",
    "Knight",
    "Elite Knight",
  ],
  requiredLevel: 1,
  requiredMagicLevel: 0,
  manaCost: 0,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "energy",
  formula: {
    kind: "level-magic",
    minimum: () => 3,
    maximum: () => 5,
  },
  effectId: 38,
  missileId: 5,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
