import type { SpellDefinition } from "../../Spell";

export const paralyzeRune: SpellDefinition = {
  id: "paralyze-rune",
  numericId: 54,
  sourcePath: "data/scripts/runes/paralyze_rune.lua",
  name: "paralyze rune",
  words: null,
  origin: "rune",
  runeItemTypeId: 3165,
  charges: 1,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 54,
  requiredMagicLevel: 18,
  manaCost: 1400,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 6000,
  groupCooldownMs: [2000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "earth",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 14,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: { type: "paralyze", durationMs: 6000, speedTarget: 40 },
  casterEffectId: 15,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
