import type { SpellDefinition } from "../../Spell";

export const soulfireRune: SpellDefinition = {
  id: "soulfire-rune",
  numericId: null,
  sourcePath: "data/scripts/runes/soul_fire.lua",
  name: "soulfire rune",
  words: null,
  origin: "rune",
  runeItemTypeId: 3195,
  charges: 3,
  vocations: [
    "Knight",
    "Paladin",
    "Sorcerer",
    "Druid",
    "Elite Knight",
    "Royal Paladin",
    "Master Sorcerer",
    "Elder Druid",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 27,
  requiredMagicLevel: 7,
  manaCost: 0,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "fire",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 16,
  missileId: 4,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "fire",
    durationMs: 20_000,
    tickIntervalMs: 2000,
    tickAmounts: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
    damageType: "fire",
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
