import type { SpellDefinition } from "../../Spell";

export const suddenDeathRune: SpellDefinition = {
  id: "sudden-death-rune",
  numericId: 21,
  sourcePath: "data/scripts/runes/sudden_death.lua",
  name: "sudden death rune",
  words: null,
  origin: "rune",
  runeItemTypeId: 3155,
  charges: 3,
  vocations: [
    "Knight",
    "Paladin",
    "Sorcerer",
    "Druid",
    "Elite Knight",
    "Royal Paladin",
    "Master Sorcerer",
    "Elder Druid",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 45,
  requiredMagicLevel: 15,
  manaCost: 0,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "death",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 4.605 + 28,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 7.395 + 46,
  },
  effectId: 18,
  missileId: 32,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
