import type { SpellDefinition } from "../../Spell";

export const ultimateHealingRune: SpellDefinition = {
  id: "ultimate-healing-rune",
  numericId: 5,
  sourcePath: "data/scripts/runes/ultimate_healing_rune.lua",
  name: "ultimate healing rune",
  words: null,
  origin: "rune",
  runeItemTypeId: 3160,
  charges: 1,
  vocations: [
    "Knight",
    "Paladin",
    "Sorcerer",
    "Druid",
    "Elite Knight",
    "Royal Paladin",
    "Master Sorcerer",
    "Elder Druid",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 24,
  requiredMagicLevel: 4,
  manaCost: 0,
  soulCost: 0,
  groups: ["healing"],
  cooldownMs: 1000,
  groupCooldownMs: [1000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 7.3 + 42,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 12.4 + 90,
  },
  effectId: 13,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: "paralyze",
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: {
    targetPlayerOnly: true,
    allowSelf: true,
    excludedVocations: ["Exalted Monk"],
    casterEffectId: 0,
  },
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
