import type { BestiarySession } from "../../../hooks/useBestiarySession";
import type { BoostedSession } from "../../../hooks/useBoostedSession";
import type { BossSlotsSession } from "../../../hooks/useBossSlotsSession";
import type { BosstiarySession } from "../../../hooks/useBosstiarySession";
import type { DepotSession } from "../../../hooks/useDepotSession";
import type { ForgeSession } from "../../../hooks/useForgeSession";
import type { ImbuementSession } from "../../../hooks/useImbuementSession";
import type { GemSession } from "../../../hooks/useGemSession";
import type { GuildSession } from "../../../hooks/useGuildSession";
import type { HighscoresSession } from "../../../hooks/useHighscoresSession";
import type { HouseSession } from "../../../hooks/useHouseSession";
import type { HuntingTasksSession } from "../../../hooks/useHuntingTasksSession";
import type { MarketSession } from "../../../hooks/useMarketSession";
import type { OptimisticInventory } from "../../../hooks/useOptimisticInventory";
import type { OutfitSession } from "../../../hooks/useOutfitSession";
import type { PartySession } from "../../../hooks/usePartySession";
import type { PreySession } from "../../../hooks/usePreySession";
import type { ProfileSession } from "../../../hooks/useProfileSession";
import type { TradeSession } from "../../../hooks/useTradeSession";
import type { TrackerSession } from "../../../hooks/useTrackerSession";
import type { VipSession } from "../../../hooks/useVipSession";
import type { WheelSession } from "../../../hooks/useWheelSession";
import type { PendingItemOp } from "../../../lib/inventory/PendingItemOp";

export interface GameWindowSessionActions {
  inventory: Omit<OptimisticInventory, "inventory">;
  depot: Omit<DepotSession, "session">;
  market: Omit<MarketSession, "session">;
  trade: Omit<TradeSession, "session">;
  party: Omit<PartySession, "state">;
  guild: Omit<GuildSession, "state">;
  house: Omit<HouseSession, "state">;
  vip: Omit<VipSession, "state">;
  highscores: Omit<HighscoresSession, "state">;
  bestiary: Omit<BestiarySession, "state">;
  bosstiary: Omit<BosstiarySession, "state">;
  wheel: Omit<WheelSession, "state">;
  gems: Omit<GemSession, "state">;
  outfit: Omit<OutfitSession, "state">;
  profile: Omit<ProfileSession, "state">;
  prey: Omit<PreySession, "state">;
  huntingTasks: Omit<HuntingTasksSession, "state">;
  boosted: Omit<BoostedSession, "state">;
  tracker: Omit<TrackerSession, "state">;
  bossSlots: Omit<BossSlotsSession, "state">;
  forge: Omit<ForgeSession, "state">;
  imbuement: Omit<ImbuementSession, "state">;
  dispatchItemOpChecked: (op: PendingItemOp) => boolean;
}
