import type { AnimusSessionState } from "../../../hooks/useAnimusSession";
import type { BestiarySessionState } from "../../../hooks/useBestiarySession";
import type { BoostedSessionState } from "../../../hooks/useBoostedSession";
import type { BossSlotsSessionState } from "../../../hooks/useBossSlotsSession";
import type { BosstiarySessionState } from "../../../hooks/useBosstiarySession";
import type { CyclopediaSessionState } from "../../../hooks/useCyclopediaSession";
import type { DepotSessionState } from "../../../hooks/useDepotSession";
import type { ForgeSessionState } from "../../../hooks/useForgeSession";
import type { ImbuementSessionState } from "../../../hooks/useImbuementSession";
import type { GemSessionState } from "../../../hooks/useGemSession";
import type { GuildSessionState } from "../../../hooks/useGuildSession";
import type { HighscoresSessionState } from "../../../hooks/useHighscoresSession";
import type { HouseSessionState } from "../../../hooks/useHouseSession";
import type { HuntingTasksSessionState } from "../../../hooks/useHuntingTasksSession";
import type { MarketSessionState } from "../../../hooks/useMarketSession";
import type { OptimisticInventory } from "../../../hooks/useOptimisticInventory";
import type { OutfitSessionState } from "../../../hooks/useOutfitSession";
import type { PartySessionState } from "../../../hooks/usePartySession";
import type { PreySessionState } from "../../../hooks/usePreySession";
import type { ProficiencySessionState } from "../../../hooks/useProficiencySession";
import type { ProfileSessionState } from "../../../hooks/useProfileSession";
import type { TradeSessionState } from "../../../hooks/useTradeSession";
import type { TrackerSessionState } from "../../../hooks/useTrackerSession";
import type { VipSessionState } from "../../../hooks/useVipSession";
import type { WheelSessionState } from "../../../hooks/useWheelSession";

export interface GameWindowSessions {
  inventory: OptimisticInventory["inventory"];
  depot: DepotSessionState | null;
  market: MarketSessionState | null;
  trade: TradeSessionState | null;
  party: PartySessionState;
  guild: GuildSessionState;
  house: HouseSessionState;
  vip: VipSessionState;
  highscores: HighscoresSessionState;
  bestiary: BestiarySessionState;
  bosstiary: BosstiarySessionState;
  wheel: WheelSessionState;
  gems: GemSessionState;
  outfit: OutfitSessionState;
  profile: ProfileSessionState;
  prey: PreySessionState;
  huntingTasks: HuntingTasksSessionState;
  boosted: BoostedSessionState;
  tracker: TrackerSessionState;
  bossSlots: BossSlotsSessionState;
  forge: ForgeSessionState;
  imbuement: ImbuementSessionState;
  proficiency: ProficiencySessionState;
  animus: AnimusSessionState;
  cyclopedia: CyclopediaSessionState;
}
