#!/usr/bin/env node
// Generates the exhaustive vocation-coefficient fixture from the pinned Canary
// vocations.xml. Every gameplay coefficient in
// server/src/progression/vocationDefinitions.ts is cross-checked against this
// fixture by vocationCoefficients.test.ts, so any drift (or an unclassified new
// coefficient) fails. Canary XML is never loaded at runtime — this is a
// build-time transcription of static balance data.
//
// Usage: node tools/buildVocationCoefficientFixture.mjs [path-to-canary]
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const canaryRoot = process.argv[2] ?? join(here, "../../canary");
const xmlPath = join(canaryRoot, "data/XML/vocations.xml");
const outPath = join(
  here,
  "../server/src/progression/vocationCoefficientFixture.json",
);

// Canary skill ids → project skill names.
const SKILL_NAMES = [
  "fist",
  "club",
  "sword",
  "axe",
  "distance",
  "shielding",
  "fishing",
];

const attrs = (block) => {
  const out = {};
  for (const match of block.matchAll(/([A-Za-z]+)\s*=\s*"([^"]*)"/g)) {
    out[match[1]] = match[2];
  }
  return out;
};

const num = (value) => {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) {
    throw new Error(`expected a number, got ${JSON.stringify(value)}`);
  }
  return parsed;
};

const xml = readFileSync(xmlPath, "utf8");
const fixture = {};
for (const match of xml.matchAll(/<vocation\b([^>]*)>([\s\S]*?)<\/vocation>/g)) {
  const head = attrs(`<${match[1]}>`);
  const body = match[2];
  // The project does not ship the internal "None" vocation.
  if (head.name === "None") continue;

  const formula = attrs(/<formula\b([^/>]*)\/?>/.exec(body)?.[1] ?? "");
  const mitigation = attrs(/<mitigation\b([^/>]*)\/?>/.exec(body)?.[1] ?? "");
  const skillMultipliers = {};
  for (const skill of body.matchAll(/<skill\b([^/>]*)\/?>/g)) {
    const skillAttrs = attrs(skill[1]);
    const name = SKILL_NAMES[num(skillAttrs.id)];
    if (!name) throw new Error(`unknown skill id ${skillAttrs.id}`);
    skillMultipliers[name] = num(skillAttrs.multiplier);
  }

  fixture[head.name] = {
    numericId: num(head.id),
    gains: {
      health: num(head.gainhp),
      mana: num(head.gainmana),
      capacity: num(head.gaincap),
    },
    regeneration: {
      healthIntervalMs: num(head.gainhpticks),
      healthAmount: num(head.gainhpamount),
      manaIntervalMs: num(head.gainmanaticks),
      manaAmount: num(head.gainmanaamount),
      soulIntervalMs: num(head.gainsoulticks),
      // Canary has no gainsoulamount attribute; the engine regenerates 1 soul
      // per tick for every vocation.
      soulAmount: 1,
    },
    maxSoul: num(head.soulmax),
    attackSpeedMs: num(head.attackspeed),
    baseSpeed: num(head.basespeed),
    magicProgressionMultiplier: num(head.manamultiplier),
    skillProgressionMultipliers: {
      fist: skillMultipliers.fist,
      club: skillMultipliers.club,
      sword: skillMultipliers.sword,
      axe: skillMultipliers.axe,
      distance: skillMultipliers.distance,
      shielding: skillMultipliers.shielding,
      fishing: skillMultipliers.fishing,
    },
    formulas: {
      meleeDamage: num(formula.meleeDamage),
      distanceDamage: num(formula.distDamage),
      defense: num(formula.defense),
      armor: num(formula.armor),
      mitigation: num(mitigation.multiplier),
      primaryShield: num(mitigation.primaryShield),
      secondaryShield: num(mitigation.secondaryShield),
    },
  };
}

const output = {
  formatVersion: 1,
  source: "canary a879c9312e34 data/XML/vocations.xml",
  note: "Generated by tools/buildVocationCoefficientFixture.mjs; do not hand-edit.",
  vocations: fixture,
};
writeFileSync(outPath, `${JSON.stringify(output, null, 2)}\n`);
console.log(`wrote ${Object.keys(fixture).length} vocations to ${outPath}`);
