import type { SpellDefinition } from "../../Spell";

export const adanaAni: SpellDefinition = {
  id: "adana-ani",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/paralyze_rune.lua",
  name: "Paralyze Rune",
  words: "adana ani",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 54,
  requiredMagicLevel: 0,
  manaCost: 1400,
  soulCost: 3,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3147, targetItemTypeId: 3165, count: 1 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
