import type { SpellDefinition } from "../../Spell";

export const adevoMasHur: SpellDefinition = {
  id: "adevo-mas-hur",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/explosion_rune.lua",
  name: "Explosion Rune",
  words: "adevo mas hur",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid", "Sorcerer", "Master Sorcerer"],
  requiredLevel: 31,
  requiredMagicLevel: 0,
  manaCost: 570,
  soulCost: 4,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3147, targetItemTypeId: 3200, count: 6 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
