import type { SpellDefinition } from "../../Spell";

export const adevoMasPox: SpellDefinition = {
  id: "adevo-mas-pox",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/poison_bomb_rune.lua",
  name: "Poison Bomb Rune",
  words: "adevo mas pox",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 25,
  requiredMagicLevel: 0,
  manaCost: 520,
  soulCost: 2,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3147, targetItemTypeId: 3173, count: 2 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
