import type { SpellDefinition } from "../../Spell";

export const adevoGravPox: SpellDefinition = {
  id: "adevo-grav-pox",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/poison_field_rune.lua",
  name: "Poison Field Rune",
  words: "adevo grav pox",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid", "Sorcerer", "Master Sorcerer"],
  requiredLevel: 14,
  requiredMagicLevel: 0,
  manaCost: 200,
  soulCost: 1,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3147, targetItemTypeId: 3172, count: 3 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
