import type { SpellDefinition } from "../../Spell";

export const adevoGravTera: SpellDefinition = {
  id: "adevo-grav-tera",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/magic_wall_rune.lua",
  name: "Magic Wall Rune",
  words: "adevo grav tera",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 32,
  requiredMagicLevel: 0,
  manaCost: 750,
  soulCost: 5,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3147, targetItemTypeId: 3180, count: 3 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
