import type { SpellDefinition } from "../../Spell";

export const adevoMasVis: SpellDefinition = {
  id: "adevo-mas-vis",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/energy_bomb_rune.lua",
  name: "Energy Bomb Rune",
  words: "adevo mas vis",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 37,
  requiredMagicLevel: 0,
  manaCost: 880,
  soulCost: 5,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3147, targetItemTypeId: 3149, count: 2 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
