import type { SpellDefinition } from "../../Spell";

export const aditoGrav: SpellDefinition = {
  id: "adito-grav",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/destroy_field_rune.lua",
  name: "Destroy Field Rune",
  words: "adito grav",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: [
    "Druid",
    "Elder Druid",
    "Paladin",
    "Royal Paladin",
    "Sorcerer",
    "Master Sorcerer",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 17,
  requiredMagicLevel: 0,
  manaCost: 120,
  soulCost: 2,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3147, targetItemTypeId: 3148, count: 3 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
