import type { SpellDefinition } from "../../Spell";

export const adoriMasFlam: SpellDefinition = {
  id: "adori-mas-flam",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/great_fireball_rune.lua",
  name: "Great Fireball Rune",
  words: "adori mas flam",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 30,
  requiredMagicLevel: 0,
  manaCost: 530,
  soulCost: 3,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3147, targetItemTypeId: 3191, count: 4 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
