import type { SpellDefinition } from "../../Spell";

export const adoriInfirVis: SpellDefinition = {
  id: "adori-infir-vis",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/lightest_missile_rune.lua",
  name: "Lightest Missile Rune",
  words: "adori infir vis",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid", "Sorcerer", "Master Sorcerer"],
  requiredLevel: 1,
  requiredMagicLevel: 0,
  manaCost: 6,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3147, targetItemTypeId: 21_352, count: 10 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
