import type { SpellDefinition } from "../../Spell";

export const adoriBlank: SpellDefinition = {
  id: "adori-blank",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/blank_rune.lua",
  name: "Blank Rune",
  words: "adori blank",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: [
    "Druid",
    "Paladin",
    "Sorcerer",
    "Elder Druid",
    "Royal Paladin",
    "Master Sorcerer",
  ],
  requiredLevel: 20,
  requiredMagicLevel: 0,
  manaCost: 50,
  soulCost: 1,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 0, targetItemTypeId: 3147, count: 1 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
