import type { SpellDefinition } from "../../Spell";

export const adoriInfirMasTera: SpellDefinition = {
  id: "adori-infir-mas-tera",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/light_stone_shower_rune.lua",
  name: "Light Stone Shower Rune",
  words: "adori infir mas tera",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid", "Sorcerer", "Master Sorcerer"],
  requiredLevel: 1,
  requiredMagicLevel: 0,
  manaCost: 6,
  soulCost: 3,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3147, targetItemTypeId: 21_351, count: 4 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
