import type { SpellDefinition } from "../../Spell";

export const adoriSan: SpellDefinition = {
  id: "adori-san",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/holy_missile_rune.lua",
  name: "Holy Missile Rune",
  words: "adori san",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 27,
  requiredMagicLevel: 0,
  manaCost: 300,
  soulCost: 3,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3147, targetItemTypeId: 3182, count: 5 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
