import type { SpellDefinition } from "../../Spell";

export const adoriDisMinVis: SpellDefinition = {
  id: "adori-dis-min-vis",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/lightest_magic_missile_rune.lua",
  name: "Lightest Magic Missile",
  words: "adori dis min vis",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: [
    "Knight",
    "Paladin",
    "Sorcerer",
    "Druid",
    "Elite Knight",
    "Royal Paladin",
    "Master Sorcerer",
    "Elder Druid",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 1,
  requiredMagicLevel: 0,
  manaCost: 5,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3147, targetItemTypeId: 3174, count: 10 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
