import type { SpellDefinition } from "../../Spell";

export const adoriMinVis: SpellDefinition = {
  id: "adori-min-vis",
  numericId: null,
  sourcePath: "data/scripts/spells/conjuring/light_magic_missile_rune.lua",
  name: "Light Magic Missile Rune",
  words: "adori min vis",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid", "Sorcerer", "Master Sorcerer"],
  requiredLevel: 15,
  requiredMagicLevel: 0,
  manaCost: 120,
  soulCost: 1,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3147, targetItemTypeId: 3174, count: 10 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
