import type { SpellDefinition } from "../../Spell";

export const exetaCon: SpellDefinition = {
  id: "exeta-con",
  numericId: 110,
  sourcePath: "data/scripts/spells/conjuring/enchant_spear.lua",
  name: "Enchant Spear",
  words: "exeta con",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 45,
  requiredMagicLevel: 0,
  manaCost: 350,
  soulCost: 3,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3277, targetItemTypeId: 7367, count: 1 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
