import type { SpellDefinition } from "../../Spell";

export const exetaVis: SpellDefinition = {
  id: "exeta-vis",
  numericId: 92,
  sourcePath: "data/scripts/spells/conjuring/enchant_staff.lua",
  name: "Enchant Staff",
  words: "exeta vis",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Master Sorcerer"],
  requiredLevel: 41,
  requiredMagicLevel: 0,
  manaCost: 80,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 3289, targetItemTypeId: 3321, count: 1 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
