import type { SpellDefinition } from "../../Spell";

export const exevoInfirCon: SpellDefinition = {
  id: "exevo-infir-con",
  numericId: 176,
  sourcePath: "data/scripts/spells/conjuring/arrow_call.lua",
  name: "Arrow Call",
  words: "exevo infir con",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 1,
  requiredMagicLevel: 0,
  manaCost: 10,
  soulCost: 1,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 0, targetItemTypeId: 21_470, count: 3 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
