import type { SpellDefinition } from "../../Spell";

export const exevoGranMort: SpellDefinition = {
  id: "exevo-gran-mort",
  numericId: 92,
  sourcePath: "data/scripts/spells/conjuring/conjure_wand_of_darkness.lua",
  name: "Conjure Wand of Darkness",
  words: "exevo gran mort",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 41,
  requiredMagicLevel: 0,
  manaCost: 250,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 1_800_000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 0, targetItemTypeId: 25_760, count: 1 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
