import type { SpellDefinition } from "../../Spell";

export const exevoConGrav: SpellDefinition = {
  id: "exevo-con-grav",
  numericId: 109,
  sourcePath: "data/scripts/spells/conjuring/conjure_piercing_bolt.lua",
  name: "Conjure Piercing Bolt",
  words: "exevo con grav",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 33,
  requiredMagicLevel: 0,
  manaCost: 180,
  soulCost: 3,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 0, targetItemTypeId: 7363, count: 5 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
