import type { SpellDefinition } from "../../Spell";

export const exevoConVis: SpellDefinition = {
  id: "exevo-con-vis",
  numericId: 95,
  sourcePath: "data/scripts/spells/conjuring/conjure_power_bolt.lua",
  name: "Conjure Power Bolt",
  words: "exevo con vis",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Royal Paladin"],
  requiredLevel: 59,
  requiredMagicLevel: 0,
  manaCost: 700,
  soulCost: 4,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 0, targetItemTypeId: 3450, count: 10 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
