import type { SpellDefinition } from "../../Spell";

export const exevoConHur: SpellDefinition = {
  id: "exevo-con-hur",
  numericId: 108,
  sourcePath: "data/scripts/spells/conjuring/conjure_sniper_arrow.lua",
  name: "Conjure Sniper Arrow",
  words: "exevo con hur",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 24,
  requiredMagicLevel: 0,
  manaCost: 160,
  soulCost: 3,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 0, targetItemTypeId: 7364, count: 5 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
