import type { SpellDefinition } from "../../Spell";

export const exevoGranConGrav: SpellDefinition = {
  id: "exevo-gran-con-grav",
  numericId: 191,
  sourcePath: "data/scripts/spells/conjuring/conjure_royal_star.lua",
  name: "Conjure Royal Star",
  words: "exevo gran con grav",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 150,
  requiredMagicLevel: 0,
  manaCost: 1000,
  soulCost: 0,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 0, targetItemTypeId: 25_759, count: 30 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
