import type { SpellDefinition } from "../../Spell";

export const exevoConPox: SpellDefinition = {
  id: "exevo-con-pox",
  numericId: 48,
  sourcePath: "data/scripts/spells/conjuring/conjure_poisoned_arrow.lua",
  name: "Conjure Poisoned Arrow",
  words: "exevo con pox",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 16,
  requiredMagicLevel: 0,
  manaCost: 130,
  soulCost: 2,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 0, targetItemTypeId: 3448, count: 7 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
