import type { SpellDefinition } from "../../Spell";

export const exevoConFlam: SpellDefinition = {
  id: "exevo-con-flam",
  numericId: 49,
  sourcePath: "data/scripts/spells/conjuring/conjure_explosive_arrow.lua",
  name: "Conjure Explosive Arrow",
  words: "exevo con flam",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 25,
  requiredMagicLevel: 0,
  manaCost: 290,
  soulCost: 3,
  groups: ["support"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "healing",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: { sourceItemTypeId: 0, targetItemTypeId: 3449, count: 8 },
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
