import type { SpellDefinition } from "../../Spell";

export const exevoGranMasTera: SpellDefinition = {
  id: "exevo-gran-mas-tera",
  numericId: 56,
  sourcePath: "data/scripts/spells/attack/wrath_of_nature.lua",
  name: "Wrath of Nature",
  words: "exevo gran mas tera",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 55,
  requiredMagicLevel: 0,
  manaCost: 700,
  soulCost: 0,
  groups: ["attack", "focus"],
  cooldownMs: 40_000,
  groupCooldownMs: [4000, 40_000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: false,
  damageType: "earth",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 5,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 10,
  },
  effectId: 46,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [
      { x: 0, y: -6 },
      { x: -1, y: -5 },
      { x: 0, y: -5 },
      { x: 1, y: -5 },
      { x: -2, y: -4 },
      { x: -1, y: -4 },
      { x: 0, y: -4 },
      { x: 1, y: -4 },
      { x: 2, y: -4 },
      { x: -3, y: -3 },
      { x: -2, y: -3 },
      { x: -1, y: -3 },
      { x: 0, y: -3 },
      { x: 1, y: -3 },
      { x: 2, y: -3 },
      { x: 3, y: -3 },
      { x: -4, y: -2 },
      { x: -3, y: -2 },
      { x: -2, y: -2 },
      { x: -1, y: -2 },
      { x: 0, y: -2 },
      { x: 1, y: -2 },
      { x: 2, y: -2 },
      { x: 3, y: -2 },
      { x: 4, y: -2 },
      { x: -5, y: -1 },
      { x: -4, y: -1 },
      { x: -3, y: -1 },
      { x: -2, y: -1 },
      { x: -1, y: -1 },
      { x: 0, y: -1 },
      { x: 1, y: -1 },
      { x: 2, y: -1 },
      { x: 3, y: -1 },
      { x: 4, y: -1 },
      { x: 5, y: -1 },
      { x: -6, y: 0 },
      { x: -5, y: 0 },
      { x: -4, y: 0 },
      { x: -3, y: 0 },
      { x: -2, y: 0 },
      { x: -1, y: 0 },
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 2, y: 0 },
      { x: 3, y: 0 },
      { x: 4, y: 0 },
      { x: 5, y: 0 },
      { x: 6, y: 0 },
      { x: -5, y: 1 },
      { x: -4, y: 1 },
      { x: -3, y: 1 },
      { x: -2, y: 1 },
      { x: -1, y: 1 },
      { x: 0, y: 1 },
      { x: 1, y: 1 },
      { x: 2, y: 1 },
      { x: 3, y: 1 },
      { x: 4, y: 1 },
      { x: 5, y: 1 },
      { x: -4, y: 2 },
      { x: -3, y: 2 },
      { x: -2, y: 2 },
      { x: -1, y: 2 },
      { x: 0, y: 2 },
      { x: 1, y: 2 },
      { x: 2, y: 2 },
      { x: 3, y: 2 },
      { x: 4, y: 2 },
      { x: -3, y: 3 },
      { x: -2, y: 3 },
      { x: -1, y: 3 },
      { x: 0, y: 3 },
      { x: 1, y: 3 },
      { x: 2, y: 3 },
      { x: 3, y: 3 },
      { x: -2, y: 4 },
      { x: -1, y: 4 },
      { x: 0, y: 4 },
      { x: 1, y: 4 },
      { x: 2, y: 4 },
      { x: -1, y: 5 },
      { x: 0, y: 5 },
      { x: 1, y: 5 },
      { x: 0, y: 6 },
    ],
    directional: false,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
