import type { SpellDefinition } from "../../Spell";

export const exevoVisLux: SpellDefinition = {
  id: "exevo-vis-lux",
  numericId: 22,
  sourcePath: "data/scripts/spells/attack/energy_beam.lua",
  name: "Energy Beam",
  words: "exevo vis lux",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 23,
  requiredMagicLevel: 0,
  manaCost: 40,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 4000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: true,
  targetKind: "direction",
  aggressive: false,
  needWeapon: false,
  damageType: "energy",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 1.8 + 11,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 3 + 19,
  },
  effectId: 12,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [
      { x: 0, y: -4 },
      { x: 0, y: -3 },
      { x: 0, y: -2 },
      { x: 0, y: -1 },
      { x: 0, y: 0 },
    ],
    diagonalOffsets: [
      { x: -4, y: -4 },
      { x: -3, y: -3 },
      { x: -2, y: -2 },
      { x: -1, y: -1 },
      { x: 0, y: 0 },
    ],
    directional: true,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
