import type { SpellDefinition } from "../../Spell";

export const exevoTeraHur: SpellDefinition = {
  id: "exevo-tera-hur",
  numericId: 120,
  sourcePath: "data/scripts/spells/attack/terra_wave.lua",
  name: "Terra Wave",
  words: "exevo tera hur",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 38,
  requiredMagicLevel: 0,
  manaCost: 170,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 4000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "direction",
  aggressive: false,
  needWeapon: false,
  damageType: "earth",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 3.5,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 7,
  },
  effectId: 46,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [
      { x: -1, y: -4 },
      { x: 0, y: -4 },
      { x: 1, y: -4 },
      { x: -1, y: -3 },
      { x: 0, y: -3 },
      { x: 1, y: -3 },
      { x: -1, y: -2 },
      { x: 0, y: -2 },
      { x: 1, y: -2 },
      { x: 0, y: -1 },
      { x: 0, y: 0 },
    ],
    diagonalOffsets: [
      { x: -4, y: -4 },
      { x: -3, y: -4 },
      { x: -2, y: -4 },
      { x: -4, y: -3 },
      { x: -3, y: -3 },
      { x: -2, y: -3 },
      { x: -4, y: -2 },
      { x: -3, y: -2 },
      { x: -2, y: -2 },
      { x: -1, y: -1 },
      { x: 0, y: 0 },
    ],
    directional: true,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
