import type { SpellDefinition } from "../../Spell";

export const exevoDisFlamHur: SpellDefinition = {
  id: "exevo-dis-flam-hur",
  numericId: 167,
  sourcePath: "data/scripts/spells/attack/practise_fire_wave.lua",
  name: "Practise Fire Wave",
  words: "exevo dis flam hur",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: [
    "Knight",
    "Paladin",
    "Sorcerer",
    "Druid",
    "Elite Knight",
    "Royal Paladin",
    "Master Sorcerer",
    "Elder Druid",
    "Monk",
    "Exalted Monk",
  ],
  requiredLevel: 1,
  requiredMagicLevel: 0,
  manaCost: 5,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 4000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "direction",
  aggressive: false,
  needWeapon: false,
  damageType: "fire",
  formula: {
    kind: "level-magic",
    minimum: () => 11,
    maximum: () => 14,
  },
  effectId: 16,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [
      { x: -2, y: -3 },
      { x: -1, y: -3 },
      { x: 0, y: -3 },
      { x: 1, y: -3 },
      { x: 2, y: -3 },
      { x: -1, y: -2 },
      { x: 0, y: -2 },
      { x: 1, y: -2 },
      { x: -1, y: -1 },
      { x: 0, y: -1 },
      { x: 1, y: -1 },
      { x: 0, y: 0 },
    ],
    diagonalOffsets: [
      { x: -1, y: -5 },
      { x: -2, y: -4 },
      { x: -1, y: -4 },
      { x: -3, y: -3 },
      { x: -2, y: -3 },
      { x: -1, y: -3 },
      { x: -4, y: -2 },
      { x: -3, y: -2 },
      { x: -2, y: -2 },
      { x: -1, y: -2 },
      { x: -5, y: -1 },
      { x: -4, y: -1 },
      { x: -3, y: -1 },
      { x: -2, y: -1 },
      { x: -1, y: -1 },
      { x: 0, y: 0 },
    ],
    directional: true,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
