import type { SpellDefinition } from "../../Spell";

export const exevoFrigoHur: SpellDefinition = {
  id: "exevo-frigo-hur",
  numericId: 121,
  sourcePath: "data/scripts/spells/attack/ice_wave.lua",
  name: "Ice Wave",
  words: "exevo frigo hur",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 18,
  requiredMagicLevel: 0,
  manaCost: 25,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 4000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "direction",
  aggressive: false,
  needWeapon: false,
  damageType: "ice",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 0.81 + 4,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 2 + 12,
  },
  effectId: 42,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [
      { x: -2, y: -3 },
      { x: -1, y: -3 },
      { x: 0, y: -3 },
      { x: 1, y: -3 },
      { x: 2, y: -3 },
      { x: -1, y: -2 },
      { x: 0, y: -2 },
      { x: 1, y: -2 },
      { x: -1, y: -1 },
      { x: 0, y: -1 },
      { x: 1, y: -1 },
      { x: 0, y: 0 },
    ],
    diagonalOffsets: [
      { x: -1, y: -5 },
      { x: -2, y: -4 },
      { x: -1, y: -4 },
      { x: -3, y: -3 },
      { x: -2, y: -3 },
      { x: -1, y: -3 },
      { x: -4, y: -2 },
      { x: -3, y: -2 },
      { x: -2, y: -2 },
      { x: -1, y: -2 },
      { x: -5, y: -1 },
      { x: -4, y: -1 },
      { x: -3, y: -1 },
      { x: -2, y: -1 },
      { x: -1, y: -1 },
      { x: 0, y: 0 },
    ],
    directional: true,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
