import type { SpellDefinition } from "../../Spell";

export const exevoGranFrigoHur: SpellDefinition = {
  id: "exevo-gran-frigo-hur",
  numericId: 43,
  sourcePath: "data/scripts/spells/attack/strong_ice_wave.lua",
  name: "Strong Ice Wave",
  words: "exevo gran frigo hur",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 40,
  requiredMagicLevel: 0,
  manaCost: 170,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 8000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "direction",
  aggressive: false,
  needWeapon: false,
  damageType: "ice",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 4.5 + 20,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 7.6 + 48,
  },
  effectId: 42,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [
      { x: -1, y: -2 },
      { x: 0, y: -2 },
      { x: 1, y: -2 },
      { x: -1, y: -1 },
      { x: 0, y: -1 },
      { x: 1, y: -1 },
      { x: 0, y: 0 },
    ],
    directional: true,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
