import type { SpellDefinition } from "../../Spell";

export const exevoGranVisLux: SpellDefinition = {
  id: "exevo-gran-vis-lux",
  numericId: 23,
  sourcePath: "data/scripts/spells/attack/great_energy_beam.lua",
  name: "Great Energy Beam",
  words: "exevo gran vis lux",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 29,
  requiredMagicLevel: 0,
  manaCost: 110,
  soulCost: 0,
  groups: ["attack", "greatbeams"],
  cooldownMs: 6000,
  groupCooldownMs: [2000, 6000],
  range: 0,
  lineOfSight: true,
  targetKind: "direction",
  aggressive: false,
  needWeapon: false,
  damageType: "energy",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 4 + 0,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 7 + 0,
  },
  effectId: 38,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [
      { x: 0, y: -7 },
      { x: 0, y: -6 },
      { x: 0, y: -5 },
      { x: 0, y: -4 },
      { x: 0, y: -3 },
      { x: 0, y: -2 },
      { x: 0, y: -1 },
      { x: 0, y: 0 },
    ],
    directional: true,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
