import type { SpellDefinition } from "../../Spell";

export const exevoVisHur: SpellDefinition = {
  id: "exevo-vis-hur",
  numericId: 13,
  sourcePath: "data/scripts/spells/attack/energy_wave.lua",
  name: "Energy Wave",
  words: "exevo vis hur",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 38,
  requiredMagicLevel: 0,
  manaCost: 170,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 8000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "direction",
  aggressive: false,
  needWeapon: false,
  damageType: "energy",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 4.5 + 0,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 9 + 0,
  },
  effectId: 38,
  missileId: 5,
  blockArmor: false,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [
      { x: -1, y: -4 },
      { x: 0, y: -4 },
      { x: 1, y: -4 },
      { x: -1, y: -3 },
      { x: 0, y: -3 },
      { x: 1, y: -3 },
      { x: -1, y: -2 },
      { x: 0, y: -2 },
      { x: 1, y: -2 },
      { x: 0, y: -1 },
      { x: 0, y: 0 },
    ],
    diagonalOffsets: [
      { x: -4, y: -4 },
      { x: -3, y: -4 },
      { x: -2, y: -4 },
      { x: -4, y: -3 },
      { x: -3, y: -3 },
      { x: -2, y: -3 },
      { x: -4, y: -2 },
      { x: -3, y: -2 },
      { x: -2, y: -2 },
      { x: -1, y: -1 },
      { x: 0, y: 0 },
    ],
    directional: true,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
