import type { SpellDefinition } from "../../Spell";

export const exoriGranFlam: SpellDefinition = {
  id: "exori-gran-flam",
  numericId: 150,
  sourcePath: "data/scripts/spells/attack/strong_flame_strike.lua",
  name: "Strong Flame Strike",
  words: "exori gran flam",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 70,
  requiredMagicLevel: 0,
  manaCost: 60,
  soulCost: 0,
  groups: ["attack", "special"],
  cooldownMs: 8000,
  groupCooldownMs: [2000, 8000],
  range: 3,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: false,
  needWeapon: false,
  damageType: "fire",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 2.8 + 16,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 4.4 + 28,
  },
  effectId: 37,
  missileId: 4,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
