import type { SpellDefinition } from "../../Spell";

export const exoriInfirTera: SpellDefinition = {
  id: "exori-infir-tera",
  numericId: 174,
  sourcePath: "data/scripts/spells/attack/mud_attack.lua",
  name: "Mud Attack",
  words: "exori infir tera",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 1,
  requiredMagicLevel: 0,
  manaCost: 6,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 3,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: true,
  needWeapon: false,
  damageType: "earth",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 0.4 + 3,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 0.7 + 5,
  },
  effectId: 47,
  missileId: 39,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
