import type { SpellDefinition } from "../../Spell";

export const exoriCon: SpellDefinition = {
  id: "exori-con",
  numericId: 111,
  sourcePath: "data/scripts/spells/attack/ethereal_spear.lua",
  name: "Ethereal Spear",
  words: "exori con",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 23,
  requiredMagicLevel: 0,
  manaCost: 25,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "physical",
  formula: {
    kind: "skill",
    minimum: ({ level, skill }) => level / 5 + (skill + 25) / 3,
    maximum: ({ level, skill }) => level / 5 + skill + 25,
  },
  effectId: 10,
  missileId: 28,
  blockArmor: true,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
