import type { SpellDefinition } from "../../Spell";

export const exoriGran: SpellDefinition = {
  id: "exori-gran",
  numericId: 105,
  sourcePath: "data/scripts/spells/attack/fierce_berserk.lua",
  name: "Fierce Berserk",
  words: "exori gran",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 90,
  requiredMagicLevel: 0,
  manaCost: 340,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 6000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: true,
  damageType: "physical",
  formula: {
    kind: "skill",
    minimum: ({ level, skill, attack }) => -1 * (level / 5 + (skill + 2 * attack) * 1.1) * 1.1,
    maximum: ({ level, skill, attack }) => -1 * (level / 5 + (skill + 2 * attack) * 3) * 1.1,
  },
  effectId: 10,
  missileId: null,
  blockArmor: true,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [
      { x: -1, y: -1 },
      { x: 0, y: -1 },
      { x: 1, y: -1 },
      { x: -1, y: 0 },
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: -1, y: 1 },
      { x: 0, y: 1 },
      { x: 1, y: 1 },
    ],
    directional: false,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
