import type { SpellDefinition } from "../../Spell";

export const exoriGranCon: SpellDefinition = {
  id: "exori-gran-con",
  numericId: 57,
  sourcePath: "data/scripts/spells/attack/strong_ethereal_spear.lua",
  name: "Strong Ethereal Spear",
  words: "exori gran con",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 90,
  requiredMagicLevel: 0,
  manaCost: 55,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 8000,
  groupCooldownMs: [2000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "physical",
  formula: {
    kind: "skill",
    minimum: ({ level, skill, attack }) => (2 * skill + attack / 2500) * 2.3 + level / 5 + 7,
    maximum: ({ level, skill, attack }) => (2 * skill + attack / 1875) * 3.3 + level / 5 + 13,
  },
  effectId: 10,
  missileId: 28,
  blockArmor: true,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
