import type { SpellDefinition } from "../../Spell";

export const exoriMaxFlam: SpellDefinition = {
  id: "exori-max-flam",
  numericId: 154,
  sourcePath: "data/scripts/spells/attack/ultimate_flame_strike.lua",
  name: "Ultimate Flame Strike",
  words: "exori max flam",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 90,
  requiredMagicLevel: 0,
  manaCost: 100,
  soulCost: 0,
  groups: ["attack", "ultimatestrikes"],
  cooldownMs: 30_000,
  groupCooldownMs: [2000, 30_000],
  range: 3,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: false,
  needWeapon: false,
  damageType: "fire",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 4.5 + 35,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 7.3 + 55,
  },
  effectId: 37,
  missileId: 4,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
