import type { SpellDefinition } from "../../Spell";

export const exoriInfirCon: SpellDefinition = {
  id: "exori-infir-con",
  numericId: 169,
  sourcePath: "data/scripts/spells/attack/lesser_ethereal_spear.lua",
  name: "Lesser Ethereal Spear",
  words: "exori infir con",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 1,
  requiredMagicLevel: 0,
  manaCost: 6,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 7,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: false,
  damageType: "physical",
  formula: {
    kind: "skill",
    minimum: ({ level, skill }) => level / 5 + (skill + 9) / 3,
    maximum: ({ level, skill }) => level / 5 + skill + 9,
  },
  effectId: 10,
  missileId: 28,
  blockArmor: true,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
