import type { SpellDefinition } from "../../Spell";

export const exoriMinFlam: SpellDefinition = {
  id: "exori-min-flam",
  numericId: 169,
  sourcePath: "data/scripts/spells/attack/apprentice's_strike.lua",
  name: "Apprentice's Strike",
  words: "exori min flam",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid", "Sorcerer", "Master Sorcerer"],
  requiredLevel: 8,
  requiredMagicLevel: 0,
  manaCost: 6,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 3,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: false,
  needWeapon: false,
  damageType: "fire",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 0.4 + 3,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 0.7 + 5,
  },
  effectId: 37,
  missileId: 4,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
