import type { SpellDefinition } from "../../Spell";

export const exoriGranVis: SpellDefinition = {
  id: "exori-gran-vis",
  numericId: 151,
  sourcePath: "data/scripts/spells/attack/strong_energy_strike.lua",
  name: "Strong Energy Strike",
  words: "exori gran vis",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 80,
  requiredMagicLevel: 0,
  manaCost: 60,
  soulCost: 0,
  groups: ["attack", "special"],
  cooldownMs: 8000,
  groupCooldownMs: [2000, 8000],
  range: 3,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: false,
  needWeapon: false,
  damageType: "energy",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 2.8 + 16,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 4.4 + 28,
  },
  effectId: 38,
  missileId: 5,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
