import type { SpellDefinition } from "../../Spell";

export const exoriMaxVis: SpellDefinition = {
  id: "exori-max-vis",
  numericId: 155,
  sourcePath: "data/scripts/spells/attack/ultimate_energy_strike.lua",
  name: "Ultimate Energy Strike",
  words: "exori max vis",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 100,
  requiredMagicLevel: 0,
  manaCost: 100,
  soulCost: 0,
  groups: ["attack", "ultimatestrikes"],
  cooldownMs: 30_000,
  groupCooldownMs: [2000, 30_000],
  range: 3,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: false,
  needWeapon: false,
  damageType: "energy",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 4.5 + 35,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 7.3 + 55,
  },
  effectId: 38,
  missileId: 5,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
