import type { SpellDefinition } from "../../Spell";

export const exoriIco: SpellDefinition = {
  id: "exori-ico",
  numericId: 61,
  sourcePath: "data/scripts/spells/attack/brutal_strike.lua",
  name: "Brutal Strike",
  words: "exori ico",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 16,
  requiredMagicLevel: 0,
  manaCost: 30,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 6000,
  groupCooldownMs: [2000],
  range: 1,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: true,
  damageType: "physical",
  formula: {
    kind: "skill",
    minimum: ({ level, skill, attack }) => -1 * (skill * attack * 0.02 + 4 + level / 5) * 1.28,
    maximum: ({ level, skill, attack }) => -1 * (skill * attack * 0.04 + 9 + level / 5) * 1.28,
  },
  effectId: 10,
  missileId: null,
  blockArmor: true,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
