import type { SpellDefinition } from "../../Spell";

export const exoriFlam: SpellDefinition = {
  id: "exori-flam",
  numericId: 89,
  sourcePath: "data/scripts/spells/attack/flame_strike.lua",
  name: "Flame Strike",
  words: "exori flam",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Druid", "Master Sorcerer", "Elder Druid"],
  requiredLevel: 14,
  requiredMagicLevel: 0,
  manaCost: 20,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 3,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: false,
  needWeapon: false,
  damageType: "fire",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 1.403 + 8,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 2.203 + 13,
  },
  effectId: 37,
  missileId: 4,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
