import type { SpellDefinition } from "../../Spell";

export const exoriMaxFrigo: SpellDefinition = {
  id: "exori-max-frigo",
  numericId: 156,
  sourcePath: "data/scripts/spells/attack/ultimate_ice_strike.lua",
  name: "Ultimate Ice Strike",
  words: "exori max frigo",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 100,
  requiredMagicLevel: 0,
  manaCost: 100,
  soulCost: 0,
  groups: ["attack", "ultimatestrikes"],
  cooldownMs: 30_000,
  groupCooldownMs: [2000, 30_000],
  range: 3,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: false,
  needWeapon: false,
  damageType: "ice",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 4.5 + 35,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 7.3 + 55,
  },
  effectId: 44,
  missileId: 37,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
