import type { SpellDefinition } from "../../Spell";

export const exori: SpellDefinition = {
  id: "exori",
  numericId: 80,
  sourcePath: "data/scripts/spells/attack/berserk.lua",
  name: "Berserk",
  words: "exori",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 35,
  requiredMagicLevel: 0,
  manaCost: 115,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 4000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "self",
  aggressive: false,
  needWeapon: true,
  damageType: "physical",
  formula: {
    kind: "skill",
    minimum: ({ level, skill, attack }) => -1 * (level / 5 + (skill + attack) * 0.5) * 1.1,
    maximum: ({ level, skill, attack }) => -1 * (level / 5 + (skill + attack) * 1.5) * 1.1,
  },
  effectId: 10,
  missileId: null,
  blockArmor: true,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [
      { x: -1, y: -1 },
      { x: 0, y: -1 },
      { x: 1, y: -1 },
      { x: -1, y: 0 },
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: -1, y: 1 },
      { x: 0, y: 1 },
      { x: 1, y: 1 },
    ],
    directional: false,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
