import type { SpellDefinition } from "../../Spell";

export const exoriGranFrigo: SpellDefinition = {
  id: "exori-gran-frigo",
  numericId: 152,
  sourcePath: "data/scripts/spells/attack/strong_ice_strike.lua",
  name: "Strong Ice Strike",
  words: "exori gran frigo",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 80,
  requiredMagicLevel: 0,
  manaCost: 60,
  soulCost: 0,
  groups: ["attack", "special"],
  cooldownMs: 8000,
  groupCooldownMs: [2000, 8000],
  range: 3,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: false,
  needWeapon: false,
  damageType: "ice",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 2.8 + 16,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 4.4 + 28,
  },
  effectId: 44,
  missileId: 37,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
