import type { SpellDefinition } from "../../Spell";

export const exoriInfirMin: SpellDefinition = {
  id: "exori-infir-min",
  numericId: 168,
  sourcePath: "data/scripts/spells/attack/lesser_front_sweep.lua",
  name: "Lesser Front Sweep",
  words: "exori infir min",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 1,
  requiredMagicLevel: 0,
  manaCost: 6,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 6000,
  groupCooldownMs: [2000],
  range: 0,
  lineOfSight: false,
  targetKind: "direction",
  aggressive: false,
  needWeapon: true,
  damageType: "physical",
  formula: {
    kind: "skill",
    minimum: ({ level, skill, attack }) => -1 * (skill * attack * 0.02 + 7 + level / 5) * 1.1,
    maximum: ({ level, skill, attack }) => -1 * (skill * attack * 0.04 + 14 + level / 5) * 1.1,
  },
  effectId: 10,
  missileId: null,
  blockArmor: true,
  blockShield: false,
  area: {
    shape: "tiles",
    offsets: [{ x: -1, y: 0 }, { x: 0, y: 0 }, { x: 1, y: 0 }],
    diagonalOffsets: [{ x: 1, y: -1 }, { x: 0, y: 0 }, { x: -1, y: 1 }],
    directional: true,
  },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
