import type { SpellDefinition } from "../../Spell";

export const exoriMort: SpellDefinition = {
  id: "exori-mort",
  numericId: 87,
  sourcePath: "data/scripts/spells/attack/death_strike.lua",
  name: "Death Strike",
  words: "exori mort",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 16,
  requiredMagicLevel: 0,
  manaCost: 20,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 3,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: false,
  needWeapon: false,
  damageType: "death",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 1.403 + 8,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 2.203 + 13,
  },
  effectId: 18,
  missileId: 11,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
