import type { SpellDefinition } from "../../Spell";

export const exoriMoeIco: SpellDefinition = {
  id: "exori-moe-ico",
  numericId: 148,
  sourcePath: "data/scripts/spells/attack/physical_strike.lua",
  name: "Physical Strike",
  words: "exori moe ico",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 16,
  requiredMagicLevel: 0,
  manaCost: 20,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 3,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: false,
  needWeapon: false,
  damageType: "physical",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 1.403 + 8,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 2.203 + 13,
  },
  effectId: 5,
  missileId: 41,
  blockArmor: true,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
