import type { SpellDefinition } from "../../Spell";

export const exoriGranIco: SpellDefinition = {
  id: "exori-gran-ico",
  numericId: 62,
  sourcePath: "data/scripts/spells/attack/annihilation.lua",
  name: "Annihilation",
  words: "exori gran ico",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 110,
  requiredMagicLevel: 0,
  manaCost: 300,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 30_000,
  groupCooldownMs: [2000],
  range: 1,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: true,
  damageType: "physical",
  formula: {
    kind: "skill",
    minimum: ({ level, skill, attack }) => -1 * (skill * attack * 0.17 + 13 + level / 5) * 1.28,
    maximum: ({ level, skill, attack }) => -1 * (skill * attack * 0.2 + 34 + level / 5) * 1.28,
  },
  effectId: 10,
  missileId: null,
  blockArmor: true,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
