import type { SpellDefinition } from "../../Spell";

export const exoriHur: SpellDefinition = {
  id: "exori-hur",
  numericId: 107,
  sourcePath: "data/scripts/spells/attack/whirlwind_throw.lua",
  name: "Whirlwind Throw",
  words: "exori hur",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight"],
  requiredLevel: 28,
  requiredMagicLevel: 0,
  manaCost: 40,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 6000,
  groupCooldownMs: [2000],
  range: 5,
  lineOfSight: true,
  targetKind: "target",
  aggressive: false,
  needWeapon: true,
  damageType: "physical",
  formula: {
    kind: "skill",
    minimum: ({ level, skill, attack }) => -1 * (level / 5 + (skill + attack) / 3) * 1.28,
    maximum: ({ level, skill, attack }) => -1 * (level / 5 + skill + attack) * 1.28,
  },
  effectId: 10,
  missileId: null,
  blockArmor: true,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
