import type { SpellDefinition } from "../../Spell";

export const exoriAmpVis: SpellDefinition = {
  id: "exori-amp-vis",
  numericId: 149,
  sourcePath: "data/scripts/spells/attack/lightning.lua",
  name: "Lightning",
  words: "exori amp vis",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 55,
  requiredMagicLevel: 0,
  manaCost: 60,
  soulCost: 0,
  groups: ["attack", "special"],
  cooldownMs: 8000,
  groupCooldownMs: [2000, 8000],
  range: 4,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: false,
  needWeapon: false,
  damageType: "energy",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 2.2 + 12,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 3.4 + 21,
  },
  effectId: 38,
  missileId: 5,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
