import type { SpellDefinition } from "../../Spell";

export const exoriVis: SpellDefinition = {
  id: "exori-vis",
  numericId: 88,
  sourcePath: "data/scripts/spells/attack/energy_strike.lua",
  name: "Energy Strike",
  words: "exori vis",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid", "Sorcerer", "Master Sorcerer"],
  requiredLevel: 12,
  requiredMagicLevel: 0,
  manaCost: 20,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 3,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: false,
  needWeapon: false,
  damageType: "energy",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 1.403 + 8,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 2.203 + 13,
  },
  effectId: 38,
  missileId: 5,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
