import type { SpellDefinition } from "../../Spell";

export const exoriSan: SpellDefinition = {
  id: "exori-san",
  numericId: 122,
  sourcePath: "data/scripts/spells/attack/divine_missile.lua",
  name: "Divine Missile",
  words: "exori san",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 40,
  requiredMagicLevel: 0,
  manaCost: 20,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 2000,
  groupCooldownMs: [2000],
  range: 4,
  lineOfSight: true,
  targetKind: "target-or-direction",
  aggressive: false,
  needWeapon: false,
  damageType: "holy",
  formula: {
    kind: "level-magic",
    minimum: ({ level, magicLevel }) => level / 5 + magicLevel * 1.79 + 11,
    maximum: ({ level, magicLevel }) => level / 5 + magicLevel * 3 + 18,
  },
  effectId: 40,
  missileId: 38,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: null,
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
