import type { SpellDefinition } from "../../Spell";

export const utoriVis: SpellDefinition = {
  id: "utori-vis",
  numericId: 140,
  sourcePath: "data/scripts/spells/attack/electrify.lua",
  name: "Electrify",
  words: "utori vis",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 34,
  requiredMagicLevel: 0,
  manaCost: 30,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 30_000,
  groupCooldownMs: [2000],
  range: 3,
  lineOfSight: true,
  targetKind: "target",
  aggressive: true,
  needWeapon: false,
  damageType: "energy",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 38,
  missileId: 5,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "energy",
    durationMs: 75_000,
    tickIntervalMs: 3000,
    tickAmounts: [
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
    ],
    damageType: "energy",
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
