import type { SpellDefinition } from "../../Spell";

export const utoriPox: SpellDefinition = {
  id: "utori-pox",
  numericId: 142,
  sourcePath: "data/scripts/spells/attack/envenom.lua",
  name: "Envenom",
  words: "utori pox",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Druid", "Elder Druid"],
  requiredLevel: 50,
  requiredMagicLevel: 0,
  manaCost: 30,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 40_000,
  groupCooldownMs: [2000],
  range: 3,
  lineOfSight: true,
  targetKind: "target",
  aggressive: true,
  needWeapon: false,
  damageType: "earth",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 46,
  missileId: 30,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "poison",
    durationMs: 75_000,
    tickIntervalMs: 3000,
    tickAmounts: [
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
      45,
    ],
    damageType: "earth",
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
