import type { SpellDefinition } from "../../Spell";

export const utoriKor: SpellDefinition = {
  id: "utori-kor",
  numericId: 141,
  sourcePath: "data/scripts/spells/attack/inflict_wound.lua",
  name: "Inflict Wound",
  words: "utori kor",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Knight", "Elite Knight", "Monk", "Exalted Monk"],
  requiredLevel: 40,
  requiredMagicLevel: 0,
  manaCost: 30,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 30_000,
  groupCooldownMs: [2000],
  range: 1,
  lineOfSight: true,
  targetKind: "target",
  aggressive: true,
  needWeapon: false,
  damageType: "physical",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 1,
  missileId: null,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "bleeding",
    durationMs: 30_000,
    tickIntervalMs: 2000,
    tickAmounts: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
    damageType: "physical",
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
