import type { SpellDefinition } from "../../Spell";

export const utoriMort: SpellDefinition = {
  id: "utori-mort",
  numericId: 139,
  sourcePath: "data/scripts/spells/attack/curse.lua",
  name: "Curse",
  words: "utori mort",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Sorcerer", "Master Sorcerer"],
  requiredLevel: 75,
  requiredMagicLevel: 0,
  manaCost: 30,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 40_000,
  groupCooldownMs: [2000],
  range: 3,
  lineOfSight: true,
  targetKind: "target",
  aggressive: true,
  needWeapon: false,
  damageType: "death",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 39,
  missileId: 11,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "curse",
    durationMs: 165_000,
    tickIntervalMs: 3000,
    tickAmounts: [
      45,
      40,
      35,
      34,
      33,
      33,
      32,
      32,
      31,
      31,
      30,
      30,
      29,
      29,
      29,
      25,
      25,
      25,
      24,
      24,
      24,
      23,
      23,
      23,
      23,
      20,
      20,
      20,
      20,
      19,
      19,
      19,
      19,
      19,
      15,
      15,
      15,
      15,
      15,
      10,
      10,
      10,
      10,
      10,
      10,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
    ],
    damageType: "death",
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
