import type { SpellDefinition } from "../../Spell";

export const utoriSan: SpellDefinition = {
  id: "utori-san",
  numericId: 143,
  sourcePath: "data/scripts/spells/attack/holy_flash.lua",
  name: "Holy Flash",
  words: "utori san",
  origin: "spell",
  runeItemTypeId: null,
  charges: null,
  vocations: ["Paladin", "Royal Paladin"],
  requiredLevel: 70,
  requiredMagicLevel: 0,
  manaCost: 30,
  soulCost: 0,
  groups: ["attack"],
  cooldownMs: 40_000,
  groupCooldownMs: [2000],
  range: 3,
  lineOfSight: true,
  targetKind: "target",
  aggressive: true,
  needWeapon: false,
  damageType: "holy",
  formula: {
    kind: "fixed",
    minimum: () => 0,
    maximum: () => 0,
  },
  effectId: 0,
  missileId: 38,
  blockArmor: false,
  blockShield: false,
  area: { shape: "single" },
  dispel: null,
  condition: {
    type: "dazzled",
    durationMs: 27_000,
    tickIntervalMs: 3000,
    tickAmounts: [20, 20, 20, 20, 20, 20, 20, 20, 20],
    damageType: "holy",
  },
  casterEffectId: 0,
  conjure: null,
  castRules: null,
  worldAction: null,
  playerAction: null,
  wheelRevelation: null,
};
